/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.anticipos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.anticipos;
import logica.proveedor;

/**
 *
 * @author DANIEL
 */
public class TablaAnticipos extends javax.swing.JFrame {

    /**
     * Creates new form TablaAnticipos
     */
    private int fila = -1;
    private Object[][] data;
    private proveedor p = new proveedor();
    private anticipos anticipo = new anticipos();
    public TablaAnticipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelInformacion = new javax.swing.JPanel();
        TituloProveedorLB = new javax.swing.JLabel();
        IconoProveedorLB = new javax.swing.JLabel();
        CodigoProveedor_LB = new javax.swing.JLabel();
        CodigoProveedor_txt = new javax.swing.JTextField();
        Identificacion_LB = new javax.swing.JLabel();
        IdentificacionProveedor_txt = new javax.swing.JTextField();
        IdentificacionProveedor_CB = new javax.swing.JComboBox<>();
        RazonSocial_LB = new javax.swing.JLabel();
        RazonSocial_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumAnticipo_LB = new javax.swing.JLabel();
        NumAnticipo_txt = new javax.swing.JTextField();
        Motivo_LB = new javax.swing.JLabel();
        MotivoCB = new javax.swing.JComboBox<>();
        Fecha_LB = new javax.swing.JLabel();
        Fecha_txt = new javax.swing.JTextField();
        Moneda_LB = new javax.swing.JLabel();
        Moneda_CB = new javax.swing.JComboBox<>();
        MontoBS_LB = new javax.swing.JLabel();
        MontoBS_txt = new javax.swing.JTextField();
        MontoDS_LB = new javax.swing.JLabel();
        MontoDS_txt = new javax.swing.JTextField();
        AprobacionLB = new javax.swing.JLabel();
        Aprobacion_txt = new javax.swing.JTextField();
        DescuentoODPLB = new javax.swing.JLabel();
        DescontarCB = new javax.swing.JComboBox<>();
        ObservacionL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Observaciontxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Semana_txt = new javax.swing.JTextField();
        Cerrar_BT = new javax.swing.JButton();
        Seleccionar_BT = new javax.swing.JToggleButton();
        Edicion_BT = new javax.swing.JToggleButton();
        Guardar_BT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        TituloProveedorLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TituloProveedorLB.setText("Informacion del Proveedor");

        IconoProveedorLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N

        CodigoProveedor_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoProveedor_LB.setText("Codigo");

        CodigoProveedor_txt.setEditable(false);

        Identificacion_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Identificacion_LB.setText("Identificacion ");

        IdentificacionProveedor_txt.setEditable(false);

        IdentificacionProveedor_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IdentificacionProveedor_CB.setEnabled(false);

        RazonSocial_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RazonSocial_LB.setText("Razon Social");

        RazonSocial_txt.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Informacion del Anticipo");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aa.png"))); // NOI18N

        NumAnticipo_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NumAnticipo_LB.setText("Nº del Anticipo");

        NumAnticipo_txt.setEditable(false);

        Motivo_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Motivo_LB.setText("Motivo del anticipo");

        MotivoCB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        MotivoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia Prima", "Adicional", "Peaje", "Otros" }));
        MotivoCB.setEnabled(false);
        MotivoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoCBActionPerformed(evt);
            }
        });

        Fecha_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fecha_LB.setText("Fecha");

        Fecha_txt.setEditable(false);

        Moneda_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Moneda_LB.setText("Moneda a Ingresar");

        Moneda_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "$" }));
        Moneda_CB.setEnabled(false);
        Moneda_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moneda_CBActionPerformed(evt);
            }
        });

        MontoBS_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MontoBS_LB.setText("Monto en BS");

        MontoBS_txt.setEditable(false);

        MontoDS_LB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MontoDS_LB.setText("Monto en $");

        MontoDS_txt.setEditable(false);

        AprobacionLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AprobacionLB.setText("Aprobado por");

        Aprobacion_txt.setEditable(false);

        DescuentoODPLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DescuentoODPLB.setText("Descontar en ODP");

        DescontarCB.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DescontarCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SI", "NO" }));
        DescontarCB.setEnabled(false);

        ObservacionL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ObservacionL.setText("Observaciones");

        Observaciontxt.setEditable(false);
        Observaciontxt.setColumns(20);
        Observaciontxt.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Observaciontxt.setRows(5);
        jScrollPane3.setViewportView(Observaciontxt);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Semana");

        Semana_txt.setEditable(false);

        Cerrar_BT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cerrar_BT.setText("CERRAR");
        Cerrar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_BTActionPerformed(evt);
            }
        });

        Seleccionar_BT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Seleccionar_BT.setText("SELECCIONAR");
        Seleccionar_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar_BTActionPerformed(evt);
            }
        });

        Edicion_BT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Edicion_BT.setText("HABILITAR EDICION");
        Edicion_BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edicion_BTActionPerformed(evt);
            }
        });

        Guardar_BT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Guardar_BT.setText("GUARDAR CAMBIOS");

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TituloProveedorLB)
                                .addComponent(jLabel3)
                                .addGroup(PanelInformacionLayout.createSequentialGroup()
                                    .addComponent(IconoProveedorLB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelInformacionLayout.createSequentialGroup()
                                            .addComponent(CodigoProveedor_LB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CodigoProveedor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Identificacion_LB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(IdentificacionProveedor_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(IdentificacionProveedor_txt))
                                        .addGroup(PanelInformacionLayout.createSequentialGroup()
                                            .addComponent(RazonSocial_LB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(RazonSocial_txt))))
                                .addGroup(PanelInformacionLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(46, 46, 46)
                                    .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PanelInformacionLayout.createSequentialGroup()
                                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NumAnticipo_LB)
                                                .addComponent(Motivo_LB))
                                            .addGap(12, 12, 12)
                                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(MotivoCB, 0, 214, Short.MAX_VALUE)
                                                .addComponent(NumAnticipo_txt))
                                            .addGap(18, 18, 18)
                                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(PanelInformacionLayout.createSequentialGroup()
                                                    .addComponent(Fecha_LB)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Fecha_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelInformacionLayout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Semana_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(PanelInformacionLayout.createSequentialGroup()
                                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Moneda_LB)
                                                .addComponent(AprobacionLB)
                                                .addComponent(DescuentoODPLB))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(PanelInformacionLayout.createSequentialGroup()
                                                    .addComponent(Moneda_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(MontoBS_LB)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(MontoBS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(MontoDS_LB)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(MontoDS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(Aprobacion_txt)
                                                .addComponent(DescontarCB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(ObservacionL))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInformacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Guardar_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edicion_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seleccionar_BT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cerrar_BT)))
                .addContainerGap())
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloProveedorLB)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IconoProveedorLB))
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoProveedor_LB)
                            .addComponent(CodigoProveedor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Identificacion_LB)
                            .addComponent(IdentificacionProveedor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdentificacionProveedor_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RazonSocial_LB)
                            .addComponent(RazonSocial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumAnticipo_LB)
                            .addComponent(NumAnticipo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Semana_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Motivo_LB)
                            .addComponent(MotivoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha_LB)
                            .addComponent(Fecha_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Moneda_LB)
                            .addComponent(Moneda_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontoBS_LB)
                            .addComponent(MontoBS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontoDS_LB)
                            .addComponent(MontoDS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AprobacionLB)
                            .addComponent(Aprobacion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescuentoODPLB)
                    .addComponent(DescontarCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(ObservacionL)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar_BT)
                    .addComponent(Seleccionar_BT)
                    .addComponent(Edicion_BT)
                    .addComponent(Guardar_BT))
                .addGap(21, 21, 21))
        );

        jScrollPane2.setViewportView(PanelInformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MotivoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mostrarTodos();
    }//GEN-LAST:event_formWindowOpened

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int index;
        fila = tabla.rowAtPoint(evt.getPoint());
        if(fila > -1){
            NumAnticipo_txt.setText(String.valueOf(tabla.getValueAt(fila,0)));
            String motivo_anticipo = String.valueOf(tabla.getValueAt(fila,1));
            index = anticipo.motivoAnticipo(motivo_anticipo);
            MotivoCB.setSelectedIndex(index);
            Fecha_txt.setText(String.valueOf(tabla.getValueAt(fila,2)));
            Semana_txt.setText(String.valueOf(tabla.getValueAt(fila,3)));
            MontoBS_txt.setText(String.valueOf(tabla.getValueAt(fila,4)));
            MontoDS_txt.setText(String.valueOf(tabla.getValueAt(fila,5)));
            Aprobacion_txt.setText(String.valueOf(tabla.getValueAt(fila,6)));
            Observaciontxt.setText(String.valueOf(tabla.getValueAt(fila,7)));
            String descontarODP = String.valueOf(tabla.getValueAt(fila,8));
            index = anticipo.descontarODP(descontarODP);
            DescontarCB.setSelectedIndex(index);
            CodigoProveedor_txt.setText(String.valueOf(tabla.getValueAt(fila,9)));
            RazonSocial_txt.setText(String.valueOf(tabla.getValueAt(fila,10)));
            String identificacion = String.valueOf(tabla.getValueAt(fila,11));
            char tipo_cedula = identificacion.charAt(0);
            index = p.indexIdentificacion(tipo_cedula);
            IdentificacionProveedor_txt.setText(identificacion.substring(1, identificacion.length()));
            IdentificacionProveedor_CB.setSelectedIndex(index);
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void Cerrar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_BTActionPerformed
        this.dispose();
    }//GEN-LAST:event_Cerrar_BTActionPerformed

    private void Seleccionar_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar_BTActionPerformed
        if(!CodigoProveedor_txt.getText().isEmpty() && Seleccionar_BT.isSelected()){
            tabla.setVisible(false);
        } else if(!CodigoProveedor_txt.getText().isEmpty() && !Seleccionar_BT.isSelected()){
            tabla.setVisible(true);
        } else if(Edicion_BT.isSelected() && !CodigoProveedor_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NO DESELECCIONE MIENTRAS ESTA HACIENDO CAMBIOS AL ANTICIPO", "ERROR", JOptionPane.ERROR_MESSAGE);
            if(Seleccionar_BT.isSelected()){
                Seleccionar_BT.setSelected(false);
            } else {
                Seleccionar_BT.setSelected(true);
            }
        } else if(CodigoProveedor_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DEBE PRESIONAR EN LA TABLA PARA MOSTRAR A UN ANTICIPO ANTES DE SELECCIONAR", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Seleccionar_BTActionPerformed

    private void Edicion_BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edicion_BTActionPerformed
        /*
            PUEDO DEJAR QUE SE CAMBIEN LOS SIGUIENTES DATOS
            1- Motivo del Anticipo
            2- La fecha dejemosla asi
            3- Aprobado por
            4- Si se descontara en ODP
            5- El monto
        */
        //HABILITANDO
        if(Edicion_BT.isSelected()){
            MotivoCB.setEnabled(true);
            Aprobacion_txt.setEditable(true);
            DescontarCB.setEnabled(true);
            Moneda_CB.setEnabled(true);
            MontoBS_txt.setEditable(true);
        } else {
            MotivoCB.setEnabled(false);
            Aprobacion_txt.setEditable(false);
            DescontarCB.setEnabled(false);
            Moneda_CB.setEnabled(false);
        }
    }//GEN-LAST:event_Edicion_BTActionPerformed

    private void Moneda_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moneda_CBActionPerformed
        /*
            AQUI LO QUE TENGO QUE HACER ES DEPENDIENDO DE DONDE SE ENCUENTRE
            DEJO ESCRIBIR EN ESA MONEDA
            Y LA PASO POR CONVERSION A LA CONTRARIA
        */
    }//GEN-LAST:event_Moneda_CBActionPerformed
    
    private void mostrarTodos(){
        //Objeto para almacenar datos
        Object[][] data;
        String[] columNames = {"Numero", "Motivo", "Fecha", "Semana", "Monto_BS", "Monto_DS", "Aprobado Por", "Observaciones", "Descontar en ODP", "Codigo_Proveedor", "Nombre_Proveedor", "Identificacion_Proveedor"};
        try{
            data = anticipo.getDatos();
            DefaultTableModel datos = new DefaultTableModel(data, columNames);
            tabla.setModel(datos);
        }catch(SQLException ex){
            Logger.getLogger(TablaAnticipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaAnticipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaAnticipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaAnticipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaAnticipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaAnticipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AprobacionLB;
    private javax.swing.JTextField Aprobacion_txt;
    private javax.swing.JButton Cerrar_BT;
    private javax.swing.JLabel CodigoProveedor_LB;
    private javax.swing.JTextField CodigoProveedor_txt;
    private javax.swing.JComboBox<String> DescontarCB;
    private javax.swing.JLabel DescuentoODPLB;
    private javax.swing.JToggleButton Edicion_BT;
    private javax.swing.JLabel Fecha_LB;
    private javax.swing.JTextField Fecha_txt;
    private javax.swing.JButton Guardar_BT;
    private javax.swing.JLabel IconoProveedorLB;
    private javax.swing.JComboBox<String> IdentificacionProveedor_CB;
    private javax.swing.JTextField IdentificacionProveedor_txt;
    private javax.swing.JLabel Identificacion_LB;
    private javax.swing.JComboBox<String> Moneda_CB;
    private javax.swing.JLabel Moneda_LB;
    private javax.swing.JLabel MontoBS_LB;
    private javax.swing.JTextField MontoBS_txt;
    private javax.swing.JLabel MontoDS_LB;
    private javax.swing.JTextField MontoDS_txt;
    private javax.swing.JComboBox<String> MotivoCB;
    private javax.swing.JLabel Motivo_LB;
    private javax.swing.JLabel NumAnticipo_LB;
    private javax.swing.JTextField NumAnticipo_txt;
    private javax.swing.JLabel ObservacionL;
    private javax.swing.JTextArea Observaciontxt;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JLabel RazonSocial_LB;
    private javax.swing.JTextField RazonSocial_txt;
    private javax.swing.JToggleButton Seleccionar_BT;
    private javax.swing.JTextField Semana_txt;
    private javax.swing.JLabel TituloProveedorLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
