package clases.proveedores;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.proveedor;

public class CreacionProveedor extends javax.swing.JFrame {

    /**
     * Creates new form CreacionProveedor
     */
    proveedor p = new proveedor();
    Object[][] dtPer;

    String[] botones_confirmacionCrear = {"SI", "NO"};
    String identificacion;
    int tipoIdentificacion;
    String codigo = "000";
    IdentificacionProveedor IP = new IdentificacionProveedor();

    public CreacionProveedor() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeIdentificacion = new javax.swing.JPanel();
        IdentificacionProveedor = new javax.swing.JLabel();
        FotoIdentificacionv = new javax.swing.JLabel();
        CodigoL = new javax.swing.JLabel();
        Codigotxt = new javax.swing.JTextField();
        IdentificacionL = new javax.swing.JLabel();
        IdentificacionCB = new javax.swing.JComboBox<>();
        Identificaciontxt = new javax.swing.JTextField();
        RazonSocialL = new javax.swing.JLabel();
        RazonSocialtxt = new javax.swing.JTextField();
        DireccionL = new javax.swing.JLabel();
        Direcciontxt = new javax.swing.JTextField();
        TlfL = new javax.swing.JLabel();
        Tlftxt = new javax.swing.JTextField();
        MailL = new javax.swing.JLabel();
        Mailtxt = new javax.swing.JTextField();
        TipoTlftxt = new javax.swing.JTextField();
        PanelBancario = new javax.swing.JPanel();
        NameBnfL = new javax.swing.JLabel();
        IDL = new javax.swing.JLabel();
        IDCB = new javax.swing.JComboBox<>();
        NameBnftxt = new javax.swing.JTextField();
        MailBnfL = new javax.swing.JLabel();
        MailBnftxt = new javax.swing.JTextField();
        BancoL = new javax.swing.JLabel();
        NumCuentaL = new javax.swing.JLabel();
        NumCuentatxt = new javax.swing.JTextField();
        TCuentaL = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        MonedaL = new javax.swing.JLabel();
        MODL = new javax.swing.JLabel();
        InformacionBancariaL = new javax.swing.JLabel();
        LogoInformacionBancaria = new javax.swing.JLabel();
        NameAutL = new javax.swing.JLabel();
        NameAuttxt = new javax.swing.JTextField();
        IDAutL = new javax.swing.JLabel();
        IDAuttxt = new javax.swing.JTextField();
        BancoCB = new javax.swing.JComboBox<>();
        TCuentaCB = new javax.swing.JComboBox<>();
        MODCB = new javax.swing.JComboBox<>();
        MonedaCB = new javax.swing.JComboBox<>();
        idCBaut = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        LimpiarBT = new javax.swing.JButton();
        CrearBT = new javax.swing.JButton();
        CancelarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        IdentificacionProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor.setText("Identificación del Proveedor");

        FotoIdentificacionv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N

        CodigoL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoL.setText("Código (*)");

        Codigotxt.setEditable(false);
        Codigotxt.setBackground(new java.awt.Color(255, 255, 255));
        Codigotxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Codigotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigotxtActionPerformed(evt);
            }
        });

        IdentificacionL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionL.setText("Identificación (*)");

        IdentificacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IdentificacionCB.setEnabled(false);

        Identificaciontxt.setEditable(false);
        Identificaciontxt.setBackground(new java.awt.Color(255, 255, 255));
        Identificaciontxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        RazonSocialL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RazonSocialL.setText("Razón Social (*)");

        RazonSocialtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RazonSocialtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazonSocialtxtActionPerformed(evt);
            }
        });

        DireccionL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DireccionL.setText("Dirección");

        Direcciontxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TlfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TlfL.setText("Teléfono");

        Tlftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        MailL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MailL.setText("E-mail");

        Mailtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TipoTlftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout PanelDeIdentificacionLayout = new javax.swing.GroupLayout(PanelDeIdentificacion);
        PanelDeIdentificacion.setLayout(PanelDeIdentificacionLayout);
        PanelDeIdentificacionLayout.setHorizontalGroup(
            PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addComponent(FotoIdentificacionv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RazonSocialL)
                                    .addComponent(DireccionL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RazonSocialtxt)
                                    .addComponent(Direcciontxt)))
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addComponent(TlfL)
                                .addGap(33, 33, 33)
                                .addComponent(TipoTlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MailL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mailtxt))
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addComponent(CodigoL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(IdentificacionL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdentificacionProveedor)))
                .addContainerGap())
        );
        PanelDeIdentificacionLayout.setVerticalGroup(
            PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdentificacionProveedor)
                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotoIdentificacionv))
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoL)
                            .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdentificacionL)
                            .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RazonSocialL)
                            .addComponent(RazonSocialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionL)
                            .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TlfL)
                            .addComponent(Tlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailL)
                            .addComponent(Mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoTlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        NameBnfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NameBnfL.setText("Nombre del beneficiario (*)");

        IDL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDL.setText("Identificación (*)");

        IDCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "P", "J", "G" }));

        NameBnftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        MailBnfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MailBnfL.setText("E-mail del beneficiario");

        MailBnftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        BancoL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BancoL.setText("Banco (*)");

        NumCuentaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NumCuentaL.setText("Nº de Cuenta (*)");

        NumCuentatxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TCuentaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TCuentaL.setText("Tipo de cuenta (*)");

        IDtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        MonedaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MonedaL.setText("Moneda");

        MODL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MODL.setText("MOD (*)");

        InformacionBancariaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InformacionBancariaL.setText("Información Bancaria");

        LogoInformacionBancaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.jpg"))); // NOI18N

        NameAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NameAutL.setText("Nombre del Autorizado (*)");

        NameAuttxt.setEditable(false);
        NameAuttxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        IDAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDAutL.setText("Identificación del Autorizado (*)");

        IDAuttxt.setEditable(false);
        IDAuttxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        BancoCB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BancoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MERCANTIL BANCO UNIVERSAL", "BANCO DE VENEZUELA S.A BANCO UNIVERSAL", "VENEZOLANO DE CREDITO S.A BANCO UNIVERSAL", "BANCO PROVINCIAL S.A BANCO UNIVERSAL", "BANCO DEL CARIBE S.A C.A", "BANCO EXTERIOR S.A", "BANCO OCCIDENTAL DE DESCUENTO S.A C.A", "BANCO CARONI C.A BANCO UNIVERSAL", "BANESCO BANCO UNIVERSAL", "BANCO SOFITASA", "BANCO PLAZA", "BANCO DE COMERCIO EXTERIOR", "FONDO COMUN C.A BANCO UNIVERSAL", "100% BANCO, BANCO UNIVERSAL C.A", "DEL SUR BANCO UNIVERSAL, C.A", "BANCO DEL TESORO ", "BANCO AGRICOLA DE VENEZUELA C.A", "BANCRECER S.A BANCO MICROFINANCIERO", "MIBANCO BANCO DE DESARROLLO", "BANCO ACTIVO C.A", "BANCA AMIGA BANCO MICROFINANCIERO", "BANCO BICENTENARIO BANCO UNIVERSAL C.A", "BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA", "BANCO NACIONAL DE CREDITO " }));

        TCuentaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente", "Cuenta Maxima", "Cuenta Moneda Extranjera" }));

        MODCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Propia", "Cuenta Nueva", "Cuenta Autorizada" }));
        MODCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODCBActionPerformed(evt);
            }
        });

        MonedaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "$" }));

        idCBaut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        idCBaut.setEnabled(false);

        javax.swing.GroupLayout PanelBancarioLayout = new javax.swing.GroupLayout(PanelBancario);
        PanelBancario.setLayout(PanelBancarioLayout);
        PanelBancarioLayout.setHorizontalGroup(
            PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addComponent(LogoInformacionBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                .addComponent(TCuentaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MODL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MonedaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                .addComponent(IDAutL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCBaut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                                        .addComponent(NameBnfL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NameBnftxt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBancarioLayout.createSequentialGroup()
                                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                                .addComponent(BancoL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BancoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NumCuentaL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                                .addComponent(IDL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(IDCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MailBnfL)
                                                .addGap(30, 30, 30)))
                                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MailBnftxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                            .addComponent(NumCuentatxt))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PanelBancarioLayout.createSequentialGroup()
                                .addComponent(NameAutL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NameAuttxt)))
                        .addContainerGap())))
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformacionBancariaL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBancarioLayout.setVerticalGroup(
            PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addComponent(InformacionBancariaL)
                .addGap(7, 7, 7)
                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoInformacionBancaria)
                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBnfL)
                            .addComponent(NameBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailBnfL)
                            .addComponent(MailBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BancoL)
                                .addComponent(BancoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NumCuentaL)
                                .addComponent(NumCuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCuentaL)
                            .addComponent(MODL)
                            .addComponent(MonedaL)
                            .addComponent(TCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameAutL)
                            .addComponent(NameAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDAutL)
                            .addComponent(IDAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCBaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LimpiarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LimpiarBT.setText("LIMPIAR");
        LimpiarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTActionPerformed(evt);
            }
        });

        CrearBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrearBT.setText("CREAR");
        CrearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBTActionPerformed(evt);
            }
        });

        CancelarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelarBT.setText("CANCELAR");
        CancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LimpiarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CancelarBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CrearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LimpiarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBancario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDeIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBancario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CodigotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigotxtActionPerformed

    private void RazonSocialtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazonSocialtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RazonSocialtxtActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        codigo += identificacion;
        IdentificacionCB.setSelectedIndex(tipoIdentificacion);
        Identificaciontxt.setText(identificacion);
        Codigotxt.setText(codigo);
        NameAuttxt.setBackground(new Color(240,240,240));
        IDAuttxt.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed
    
    //BOTON DE CREAR PROVEEDOR
    private void CrearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBTActionPerformed
        //SE VERIFICA PRIMERO SI SE HAN RELLENADO LOS DATOS DE LOS PROVEEDORES
        if ((Codigotxt.getText().equals("")) || (Identificaciontxt.getText().equals("")) || (RazonSocialtxt.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "DEBE RELLENAR LOS CAMPOS OBLIGATORIOS", "ERROR", JOptionPane.PLAIN_MESSAGE);
        } else {
            //PRIMERO SE OBTIENEN TODOS LOS DATOS DE LOS CAMPOS
            String codigo = Codigotxt.getText();
            String identificacion = IdentificacionCB.getSelectedItem().toString();
            identificacion += Identificaciontxt.getText();
            String razon_social = RazonSocialtxt.getText();
            String direccion = Direcciontxt.getText();
            String telefono = TipoTlftxt.getText();
            telefono += Tlftxt.getText();
            String mail = Mailtxt.getText();
            String nombre_beneficiario = NameBnftxt.getText();
            String id_beneficiario = IDCB.getSelectedItem().toString();
            id_beneficiario += IDtxt.getText();
            String mail_bnf = MailBnftxt.getText();
            String banco = BancoCB.getSelectedItem().toString();
            String num_cuenta = NumCuentatxt.getText();
            String Tipo_cuenta = TCuentaCB.getSelectedItem().toString();
            String mod_cuenta = MODCB.getSelectedItem().toString();
            String moneda = MonedaCB.getSelectedItem().toString();
            String name_autorizado = NameAuttxt.getText();
            String ID_autorizado = idCBaut.getSelectedItem().toString();
            ID_autorizado += IDAuttxt.getText();
            //=====================================================================================================================================================================================================================
            p.NuevoProveedor(codigo, identificacion, razon_social, direccion, telefono, mail, nombre_beneficiario, id_beneficiario, mail_bnf, banco, num_cuenta, Tipo_cuenta, mod_cuenta, moneda, name_autorizado, ID_autorizado);
            //Llamar a la funcion de nuevo proveedor
            int index = JOptionPane.showOptionDialog(null, "CREACION EXITOSA \n \n ¿DESEA CREAR UN NUEVO PROVEEDOR?", "CONFIRMACION DE CREAR", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones_confirmacionCrear, botones_confirmacionCrear[0]);
            //si desea crear nuevo
            if (index == 0) {
                IP.setVisible(true);
                IP.modo = 1;
                this.dispose();
            } else {
                this.dispose();

            }
        }
    }//GEN-LAST:event_CrearBTActionPerformed

    private void LimpiarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTActionPerformed
        limpiar();
    }//GEN-LAST:event_LimpiarBTActionPerformed

    private void CancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarBTActionPerformed

    private void MODCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODCBActionPerformed
        if (MODCB.getSelectedItem().toString().equals("Cuenta Autorizada")) {
            NameAuttxt.setEditable(true);
            NameAuttxt.setBackground(new Color(255,255,255));
            //SE AGREGA LA ACTIVACION DEL ID COMBOBOX DEL AUTORIZADO
            idCBaut.setEnabled(true);
            IDAuttxt.setEditable(true);
            IDAuttxt.setBackground(new Color(255,255,255));
        } else if (MODCB.getSelectedItem().toString().equals("Cuenta Nueva") || MODCB.getSelectedItem().toString().equals("Cuenta Propia")) {
            NameAuttxt.setEditable(false);
            NameAuttxt.setBackground(new Color(240,240,240));
            IDAuttxt.setEditable(false);
            IDAuttxt.setBackground(new Color(240,240,240));
            idCBaut.setEnabled(false);
        }
    }//GEN-LAST:event_MODCBActionPerformed

    public void limpiar() {
        RazonSocialtxt.setText("");
        Direcciontxt.setText("");
        Tlftxt.setText("");
        TipoTlftxt.setText("");
        Mailtxt.setText("");
        NameBnftxt.setText("");
        IDCB.setSelectedIndex(0);
        IDtxt.setText("");
        MailBnftxt.setText("");
        BancoCB.setSelectedIndex(0);
        NumCuentatxt.setText("");
        TCuentaCB.setSelectedIndex(0);
        MODCB.setSelectedIndex(0);
        MonedaCB.setSelectedIndex(0);
        NameAuttxt.setText("");
        IDAuttxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionProveedor().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BancoCB;
    private javax.swing.JLabel BancoL;
    private javax.swing.JButton CancelarBT;
    private javax.swing.JLabel CodigoL;
    private javax.swing.JTextField Codigotxt;
    private javax.swing.JButton CrearBT;
    private javax.swing.JLabel DireccionL;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JLabel FotoIdentificacionv;
    private javax.swing.JLabel IDAutL;
    private javax.swing.JTextField IDAuttxt;
    private javax.swing.JComboBox<String> IDCB;
    private javax.swing.JLabel IDL;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JComboBox<String> IdentificacionCB;
    private javax.swing.JLabel IdentificacionL;
    private javax.swing.JLabel IdentificacionProveedor;
    private javax.swing.JTextField Identificaciontxt;
    private javax.swing.JLabel InformacionBancariaL;
    private javax.swing.JButton LimpiarBT;
    private javax.swing.JLabel LogoInformacionBancaria;
    private javax.swing.JComboBox<String> MODCB;
    private javax.swing.JLabel MODL;
    private javax.swing.JLabel MailBnfL;
    private javax.swing.JTextField MailBnftxt;
    private javax.swing.JLabel MailL;
    private javax.swing.JTextField Mailtxt;
    private javax.swing.JComboBox<String> MonedaCB;
    private javax.swing.JLabel MonedaL;
    private javax.swing.JLabel NameAutL;
    private javax.swing.JTextField NameAuttxt;
    private javax.swing.JLabel NameBnfL;
    private javax.swing.JTextField NameBnftxt;
    private javax.swing.JLabel NumCuentaL;
    private javax.swing.JTextField NumCuentatxt;
    private javax.swing.JPanel PanelBancario;
    private javax.swing.JPanel PanelDeIdentificacion;
    private javax.swing.JLabel RazonSocialL;
    private javax.swing.JTextField RazonSocialtxt;
    private javax.swing.JComboBox<String> TCuentaCB;
    private javax.swing.JLabel TCuentaL;
    private javax.swing.JTextField TipoTlftxt;
    private javax.swing.JLabel TlfL;
    private javax.swing.JTextField Tlftxt;
    private javax.swing.JComboBox<String> idCBaut;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
