package clases.proveedores;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.plaf.BorderUIResource;
import logica.*;

public class CreacionProveedor extends javax.swing.JFrame {

    /**
     * Creates new form CreacionProveedor
     */
    public proveedor p = new proveedor();
    public beneficiarios b = new beneficiarios();
    public Object[][] dtPer;
    private Object[][] dataBeneficiarios;
    public Tarifa_Estandar TE = new Tarifa_Estandar();
    public String[] botones_confirmacionCrear = {"SI", "NO"};
    public String identificacion;
    public int tipoIdentificacion;
    public int codigo;
    public IdentificacionProveedor IP = new IdentificacionProveedor();
    boolean bancaria = false;
    boolean tarifa = true;
    public int cod_tarifa;
    public Proveedor_Beneficiario PB = new Proveedor_Beneficiario();
    private Border borde_rojo = BorderFactory.createLineBorder(Color.RED, 1);
    //private Border borde_rojo = BorderFactory.
    private Border borde_default;
    
    public CreacionProveedor() {
        initComponents();
        setResizable(false);
        borde_default = RazonSocialtxt.getBorder();
        AlertaNumCuenta.setVisible(false);
    }
    
    public void codigo(){
        try {
            this.codigo = p.codigoSiguiente();
            String codigo = String.valueOf(this.codigo);
            Codigotxt.setText(codigo);
        } catch (SQLException ex) {
            Logger.getLogger(CreacionProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeIdentificacion = new javax.swing.JPanel();
        IdentificacionProveedor = new javax.swing.JLabel();
        FotoIdentificacionv = new javax.swing.JLabel();
        CodigoL = new javax.swing.JLabel();
        Codigotxt = new javax.swing.JTextField();
        IdentificacionL = new javax.swing.JLabel();
        IdentificacionCB = new javax.swing.JComboBox<>();
        Identificaciontxt = new javax.swing.JTextField();
        RazonSocialL = new javax.swing.JLabel();
        RazonSocialtxt = new javax.swing.JTextField();
        DireccionL = new javax.swing.JLabel();
        Direcciontxt = new javax.swing.JTextField();
        TlfL = new javax.swing.JLabel();
        Tlftxt = new javax.swing.JTextField();
        MailL = new javax.swing.JLabel();
        Mailtxt = new javax.swing.JTextField();
        TipoTlftxt = new javax.swing.JTextField();
        MunicipioLB = new javax.swing.JLabel();
        Municipiotxt = new javax.swing.JTextField();
        PanelBancario = new javax.swing.JPanel();
        NameBnfL = new javax.swing.JLabel();
        IDL = new javax.swing.JLabel();
        IDCB = new javax.swing.JComboBox<>();
        NameBnftxt = new javax.swing.JTextField();
        MailBnfL = new javax.swing.JLabel();
        MailBnftxt = new javax.swing.JTextField();
        BancoL = new javax.swing.JLabel();
        NumCuentaL = new javax.swing.JLabel();
        NumCuentatxt = new javax.swing.JTextField();
        TCuentaL = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        MODL = new javax.swing.JLabel();
        InformacionBancariaL = new javax.swing.JLabel();
        LogoInformacionBancaria = new javax.swing.JLabel();
        NameAutL = new javax.swing.JLabel();
        NameAuttxt = new javax.swing.JTextField();
        IDAutL = new javax.swing.JLabel();
        IDAuttxt = new javax.swing.JTextField();
        BancoCB = new javax.swing.JComboBox<>();
        TCuentaCB = new javax.swing.JComboBox<>();
        MODCB = new javax.swing.JComboBox<>();
        idCBaut = new javax.swing.JComboBox<>();
        BancariaBT = new javax.swing.JToggleButton();
        ListarBeneficiariosBT = new javax.swing.JComboBox<>();
        AlertaNumCuenta = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        LimpiarBT = new javax.swing.JButton();
        CrearBT = new javax.swing.JButton();
        CancelarBT = new javax.swing.JButton();
        PanelDePagos = new javax.swing.JPanel();
        IdentificacionProveedor1 = new javax.swing.JLabel();
        IdentificacionProveedor2 = new javax.swing.JLabel();
        MPCB = new javax.swing.JComboBox<>();
        IdentificacionProveedor3 = new javax.swing.JLabel();
        Cuadrillatxt = new javax.swing.JTextField();
        IdentificacionProveedor4 = new javax.swing.JLabel();
        Fletetxt = new javax.swing.JTextField();
        IdentificacionProveedor5 = new javax.swing.JLabel();
        Peajetxt = new javax.swing.JTextField();
        TarifaEstandarBT = new javax.swing.JToggleButton();
        IdentificacionProveedor6 = new javax.swing.JLabel();
        MP_Acordadotxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        IdentificacionProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor.setText("Identificación del Proveedor");

        FotoIdentificacionv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N

        CodigoL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoL.setText("Código (*)");

        Codigotxt.setEditable(false);
        Codigotxt.setBackground(new java.awt.Color(255, 255, 255));
        Codigotxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        IdentificacionL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionL.setText("Identificación (*)");

        IdentificacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IdentificacionCB.setEnabled(false);

        Identificaciontxt.setEditable(false);
        Identificaciontxt.setBackground(new java.awt.Color(255, 255, 255));
        Identificaciontxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        RazonSocialL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RazonSocialL.setText("Razón Social (*)");

        RazonSocialtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        DireccionL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DireccionL.setText("Dirección");

        Direcciontxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TlfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TlfL.setText("Teléfono");

        Tlftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Tlftxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TlftxtKeyTyped(evt);
            }
        });

        MailL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MailL.setText("E-mail");

        Mailtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TipoTlftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TipoTlftxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TipoTlftxtKeyTyped(evt);
            }
        });

        MunicipioLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MunicipioLB.setText("Municipio");

        javax.swing.GroupLayout PanelDeIdentificacionLayout = new javax.swing.GroupLayout(PanelDeIdentificacion);
        PanelDeIdentificacion.setLayout(PanelDeIdentificacionLayout);
        PanelDeIdentificacionLayout.setHorizontalGroup(
            PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addComponent(FotoIdentificacionv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RazonSocialL)
                                    .addComponent(DireccionL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                        .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MunicipioLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Municipiotxt))
                                    .addComponent(RazonSocialtxt)))
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addComponent(TlfL)
                                .addGap(33, 33, 33)
                                .addComponent(TipoTlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MailL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Mailtxt))
                            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                                .addComponent(CodigoL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(IdentificacionL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdentificacionProveedor)))
                .addContainerGap())
        );
        PanelDeIdentificacionLayout.setVerticalGroup(
            PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdentificacionProveedor)
                .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotoIdentificacionv))
                    .addGroup(PanelDeIdentificacionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoL)
                            .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdentificacionL)
                            .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RazonSocialL)
                            .addComponent(RazonSocialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionL)
                            .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MunicipioLB)
                            .addComponent(Municipiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelDeIdentificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TlfL)
                            .addComponent(Tlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailL)
                            .addComponent(Mailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoTlftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        NameBnfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NameBnfL.setText("Nombre del beneficiario (*)");

        IDL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDL.setText("Identificación (*)");

        IDCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "P", "J", "G" }));
        IDCB.setEnabled(false);

        NameBnftxt.setEditable(false);
        NameBnftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        MailBnfL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MailBnfL.setText("E-mail del beneficiario");

        MailBnftxt.setEditable(false);
        MailBnftxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        MailBnftxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailBnftxtActionPerformed(evt);
            }
        });

        BancoL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BancoL.setText("Banco (*)");

        NumCuentaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NumCuentaL.setText("Nº de Cuenta (*)");

        NumCuentatxt.setEditable(false);
        NumCuentatxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        NumCuentatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumCuentatxtKeyTyped(evt);
            }
        });

        TCuentaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TCuentaL.setText("Tipo de cuenta (*)");

        IDtxt.setEditable(false);
        IDtxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        MODL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MODL.setText("MOD (*)");

        InformacionBancariaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        InformacionBancariaL.setText("Información Bancaria");

        LogoInformacionBancaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2.jpg"))); // NOI18N

        NameAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NameAutL.setText("Nombre del Autorizado (*)");

        NameAuttxt.setEditable(false);
        NameAuttxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        IDAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDAutL.setText("Identificación del Autorizado (*)");

        IDAuttxt.setEditable(false);
        IDAuttxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        BancoCB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BancoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MERCANTIL BANCO UNIVERSAL", "BANCO DE VENEZUELA S.A BANCO UNIVERSAL", "VENEZOLANO DE CREDITO S.A BANCO UNIVERSAL", "BANCO PROVINCIAL S.A BANCO UNIVERSAL", "BANCO DEL CARIBE S.A C.A", "BANCO EXTERIOR S.A", "BANCO OCCIDENTAL DE DESCUENTO S.A C.A", "BANCO CARONI C.A BANCO UNIVERSAL", "BANESCO BANCO UNIVERSAL", "BANCO SOFITASA", "BANCO PLAZA", "BANCO DE COMERCIO EXTERIOR", "FONDO COMUN C.A BANCO UNIVERSAL", "100% BANCO, BANCO UNIVERSAL C.A", "DEL SUR BANCO UNIVERSAL, C.A", "BANCO DEL TESORO ", "BANCO AGRICOLA DE VENEZUELA C.A", "BANCRECER S.A BANCO MICROFINANCIERO", "MIBANCO BANCO DE DESARROLLO", "BANCO ACTIVO C.A", "BANCA AMIGA BANCO MICROFINANCIERO", "BANCO BICENTENARIO BANCO UNIVERSAL C.A", "BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA", "BANCO NACIONAL DE CREDITO " }));
        BancoCB.setEnabled(false);

        TCuentaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente", "Cuenta Maxima", "Cuenta Moneda Extranjera" }));
        TCuentaCB.setEnabled(false);

        MODCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Propia", "Cuenta Nueva", "Cuenta Autorizada" }));
        MODCB.setEnabled(false);
        MODCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODCBActionPerformed(evt);
            }
        });

        idCBaut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        idCBaut.setEnabled(false);

        BancariaBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BancariaBT.setText("HABILITAR INFORMACION BANCARIA");
        BancariaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancariaBTActionPerformed(evt);
            }
        });

        ListarBeneficiariosBT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo" }));
        ListarBeneficiariosBT.setEnabled(false);
        ListarBeneficiariosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBeneficiariosBTActionPerformed(evt);
            }
        });

        AlertaNumCuenta.setForeground(new java.awt.Color(255, 0, 0));
        AlertaNumCuenta.setText("Deben ser 20 carácteres numericos obligatoriamente.");

        javax.swing.GroupLayout PanelBancarioLayout = new javax.swing.GroupLayout(PanelBancario);
        PanelBancario.setLayout(PanelBancarioLayout);
        PanelBancarioLayout.setHorizontalGroup(
            PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addComponent(LogoInformacionBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(PanelBancarioLayout.createSequentialGroup()
                            .addComponent(NameBnfL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(NameBnftxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBancarioLayout.createSequentialGroup()
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelBancarioLayout.createSequentialGroup()
                                    .addComponent(BancoL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BancoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NumCuentaL))
                                .addGroup(PanelBancarioLayout.createSequentialGroup()
                                    .addComponent(IDL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IDCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(MailBnfL))
                                .addGroup(PanelBancarioLayout.createSequentialGroup()
                                    .addComponent(TCuentaL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(MODL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelBancarioLayout.createSequentialGroup()
                                    .addComponent(IDAutL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idCBaut, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IDAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MailBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AlertaNumCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumCuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                        .addComponent(NameAutL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameAuttxt)))
                .addContainerGap())
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformacionBancariaL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BancariaBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListarBeneficiariosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBancarioLayout.setVerticalGroup(
            PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBancarioLayout.createSequentialGroup()
                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InformacionBancariaL)
                    .addComponent(BancariaBT)
                    .addComponent(ListarBeneficiariosBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoInformacionBancaria)
                    .addGroup(PanelBancarioLayout.createSequentialGroup()
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameBnfL)
                            .addComponent(NameBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MailBnfL)
                            .addComponent(MailBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BancoL)
                                .addComponent(BancoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NumCuentaL)
                                .addComponent(NumCuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TCuentaL)
                                .addComponent(MODL)
                                .addComponent(TCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AlertaNumCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameAutL)
                            .addComponent(NameAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDAutL)
                            .addComponent(IDAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCBaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LimpiarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LimpiarBT.setText("LIMPIAR");
        LimpiarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTActionPerformed(evt);
            }
        });

        CrearBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrearBT.setText("CREAR");
        CrearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBTActionPerformed(evt);
            }
        });

        CancelarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelarBT.setText("CANCELAR");
        CancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LimpiarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CancelarBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CrearBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LimpiarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IdentificacionProveedor1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor1.setText("Tasas de pago");

        IdentificacionProveedor2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor2.setText("MP");

        MPCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TABLA", "ACORDADO" }));
        MPCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPCBActionPerformed(evt);
            }
        });

        IdentificacionProveedor3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor3.setText("Cuadrilla (*)");

        Cuadrillatxt.setEditable(false);

        IdentificacionProveedor4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor4.setText("Peaje (*)");

        Fletetxt.setEditable(false);

        IdentificacionProveedor5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor5.setText("Flete (*)");

        Peajetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeajetxtActionPerformed(evt);
            }
        });

        TarifaEstandarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TarifaEstandarBT.setSelected(true);
        TarifaEstandarBT.setText("TARIFA ESTANDAR");
        TarifaEstandarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifaEstandarBTActionPerformed(evt);
            }
        });

        IdentificacionProveedor6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IdentificacionProveedor6.setText("MP (Monto acordado):");

        MP_Acordadotxt.setEditable(false);

        javax.swing.GroupLayout PanelDePagosLayout = new javax.swing.GroupLayout(PanelDePagos);
        PanelDePagos.setLayout(PanelDePagosLayout);
        PanelDePagosLayout.setHorizontalGroup(
            PanelDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDePagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdentificacionProveedor1)
                .addGap(27, 27, 27)
                .addGroup(PanelDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDePagosLayout.createSequentialGroup()
                        .addComponent(IdentificacionProveedor6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MP_Acordadotxt))
                    .addGroup(PanelDePagosLayout.createSequentialGroup()
                        .addComponent(IdentificacionProveedor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IdentificacionProveedor3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cuadrillatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdentificacionProveedor5)
                .addGap(10, 10, 10)
                .addComponent(Fletetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdentificacionProveedor4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Peajetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TarifaEstandarBT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDePagosLayout.setVerticalGroup(
            PanelDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDePagosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificacionProveedor1)
                    .addComponent(IdentificacionProveedor2)
                    .addComponent(MPCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdentificacionProveedor3)
                    .addComponent(Cuadrillatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdentificacionProveedor4)
                    .addComponent(Fletetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdentificacionProveedor5)
                    .addComponent(Peajetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifaEstandarBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDePagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificacionProveedor6)
                    .addComponent(MP_Acordadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBancario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PanelDePagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelDeIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBancario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDePagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*if(identificacion.length() == 8){
            codigo += identificacion;
        } else if(identificacion.length() == 7){
            codigo += "0" + identificacion;
        }
        */
        codigo();
        IdentificacionCB.setSelectedIndex(tipoIdentificacion);
        Identificaciontxt.setText(identificacion);
        NameAuttxt.setBackground(new Color(240,240,240));
        IDAuttxt.setBackground(new Color(240,240,240));
        
        ActualizarCamposTarifa();
    }//GEN-LAST:event_formWindowOpened

    private void cargarDatosBeneficiarios(){
        
        int registros = b.cantidadRegistros();
        dataBeneficiarios = b.getDatos();
        for(int i = 0; i <= registros - 1; i++){
            String item = dataBeneficiarios[i][1].toString();
            item += "   -   " + dataBeneficiarios[i][2].toString();
            ListarBeneficiariosBT.addItem(item);
        }
    }
    
    public void ActualizarCamposTarifa(){
        // IMPRIMIR LOS DATOS DE LA TARIFA ESTANDAR
        Object[] data = TE.obtenerUltimaTarifa();
        Cuadrillatxt.setText(String.valueOf(data[1]));
        Fletetxt.setText(String.valueOf(data[2]));
        cod_tarifa = Integer.parseInt(data[0].toString());
        MPCB.setEnabled(false);
    }
    
    private boolean verificacionCompleta(){
        boolean condicion = true;
        boolean tipoTlf = false;
        String texto;
        /*
            SE PROCEDERÁ A VERIFICAR TODOS LOS CAMPOS POSIBLES
            1- Razon Social no este vacia
            2- Que ambos textos del telefono sean unicamente digitos numéricos
            3- Que el email tenga un @ y un .
            4- Verificacion de los campos de pagos sean flotantes.
            5- Si está activada la información bancaria:
                5.1- Verificar Nombre no vacio
                5.2- Identificacion no vacia y meramente numerica
                5.3- Si el correo no esta vacio, que sea valido
                5.4- Que el numero de cuenta sea meramente numerico y obligatoriamente 20 digitos
                5.5- Si esta en modo autorizado:
                    5.5.1- Que el nombre no este vacio
                    5.5.2- Que la identificacion sea valida
        */
        //1- RAZON SOCIAL
        if(RazonSocialtxt.getText().isEmpty()){
            condicion = false;
            RazonSocialtxt.setBorder(borde_rojo);
        } else {
            RazonSocialtxt.setBorder(borde_default);
        }
        //2.1- PRIMEROS 4 DIGITOS DEL TELEFONO
        if(!TipoTlftxt.getText().isEmpty() && !p.comprobacionIdentificacion(TipoTlftxt.getText())){
            TipoTlftxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!TipoTlftxt.getText().isEmpty() && p.comprobacionIdentificacion(TipoTlftxt.getText())){
            if(TipoTlftxt.getText().length() != 4){
                TipoTlftxt.setBorder(borde_rojo);
                condicion = false;
            } else {
                TipoTlftxt.setBorder(borde_default);
                tipoTlf = true;
            }
        }
        //2.2- ULTIMOS 7 DIGITOS DEL TELEFONO
        if(!TipoTlftxt.getText().isEmpty()){
            if(!Tlftxt.getText().isEmpty() && !p.comprobacionIdentificacion(Tlftxt.getText()) && tipoTlf){
                Tlftxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!Tlftxt.getText().isEmpty() && p.comprobacionIdentificacion(Tlftxt.getText()) && tipoTlf){
                if(Tlftxt.getText().length() != 7){
                    Tlftxt.setBorder(borde_rojo);
                    condicion = false;
                } else {
                    Tlftxt.setBorder(borde_default);
                }
            } else if(Tlftxt.getText().isEmpty()){
                Tlftxt.setBorder(borde_rojo);
                condicion = false;
            }
        } else if(TipoTlftxt.getText().isEmpty() && !Tlftxt.getText().isEmpty()){
            TipoTlftxt.setBorder(borde_rojo);
            Tlftxt.setBorder(borde_rojo);
            condicion = false;
        } else if(TipoTlftxt.getText().isEmpty() && Tlftxt.getText().isEmpty()){
            TipoTlftxt.setBorder(borde_default);
            Tlftxt.setBorder(borde_default);
        }
        //3- COMPROBACION DE CORREO
        if(!Mailtxt.getText().isEmpty() && !verificacionCorreo(Mailtxt.getText())){
            Mailtxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Mailtxt.getText().isEmpty() && verificacionCorreo(Mailtxt.getText())){
            Mailtxt.setBorder(borde_default);
        }
        //4.1- COMPROBACION DE MATERIA PRIMA ACORDADA
        if(MPCB.getSelectedIndex() != 0){
            if(MP_Acordadotxt.getText().isEmpty()){
                MP_Acordadotxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!MP_Acordadotxt.getText().isEmpty()){    
                if(!p.comprobacionFlotante(MP_Acordadotxt.getText())){
                    condicion = false;
                    MP_Acordadotxt.setBorder(borde_rojo);
                } else {
                    MP_Acordadotxt.setBorder(borde_default);
                }
            }
        } else {
            MP_Acordadotxt.setBorder(borde_default);
        }
        //4.2- COMPROBACION DE CUADRILLA
        if(Cuadrillatxt.getText().isEmpty()){
            Cuadrillatxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Cuadrillatxt.getText().isEmpty()){
            if(!p.comprobacionFlotante(Cuadrillatxt.getText())){
                condicion = false;
                Cuadrillatxt.setBorder(borde_rojo);
            } else {
                Cuadrillatxt.setBorder(borde_default);
            }
        }
        //4.3- COMPROBACION DE FLETE
        if(Fletetxt.getText().isEmpty()){
            Fletetxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Fletetxt.getText().isEmpty()){
            if(!p.comprobacionFlotante(Fletetxt.getText())){
                condicion = false;
                Fletetxt.setBorder(borde_rojo);
            } else {
                Fletetxt.setBorder(borde_default);
            }
        }
        //4.4- COMPROBACION DE PEAJE
        if(Peajetxt.getText().isEmpty()){
            Peajetxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Peajetxt.getText().isEmpty()){
            if(!p.comprobacionEntero(Peajetxt.getText())){
                condicion = false;
                Peajetxt.setBorder(borde_rojo);
            } else{
                Peajetxt.setBorder(borde_default);
            }
        }
        //COMPROBACION BANCARIA
        if(BancariaBT.isSelected()){
            //5.1- Nombre no vacio
            if(NameBnftxt.getText().isEmpty()){
                NameBnftxt.setBorder(borde_rojo);
                condicion = false;
            } else {
                NameBnftxt.setBorder(borde_default);
            }
            //5.2- Identificacion no vacia y meramente numerica 
            if(IDtxt.getText().isEmpty()){
                IDtxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!IDtxt.getText().isEmpty() && (IDtxt.getText().length() < 7)){
                IDtxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!IDtxt.getText().isEmpty() && !(IDtxt.getText().length() < 7)){
                if(!p.comprobacionIdentificacion(IDtxt.getText())){
                    IDtxt.setBorder(borde_rojo);
                    condicion = false;
                } else if(p.comprobacionIdentificacion(IDtxt.getText())){
                    IDtxt.setBorder(borde_default);
                }
            }
            //5.3- Si el correo no esta vacio, que sea valido
            if(!MailBnftxt.getText().isEmpty() && !verificacionCorreo(MailBnftxt.getText())){
                MailBnftxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!MailBnftxt.getText().isEmpty() && verificacionCorreo(MailBnftxt.getText())){
                MailBnftxt.setBorder(borde_default);
            }
            //5.4- Numero de cuenta no vacio, numerico y 20 digitos
            if(NumCuentatxt.getText().isEmpty()){
                NumCuentatxt.setBorder(borde_rojo);
                condicion = false;
            } else if(!NumCuentatxt.getText().isEmpty()){
                if(NumCuentatxt.getText().length() != 20){
                    NumCuentatxt.setBorder(borde_rojo);
                    AlertaNumCuenta.setVisible(true);
                    condicion = false;
                } else if(NumCuentatxt.getText().length() == 20){
                    if(!p.comprobacionIdentificacion(NumCuentatxt.getText())){
                        AlertaNumCuenta.setVisible(true);
                        NumCuentatxt.setBorder(borde_rojo);
                        condicion = false;
                    } else if(p.comprobacionIdentificacion(NumCuentatxt.getText())){
                        AlertaNumCuenta.setVisible(false);
                        NumCuentatxt.setBorder(borde_default);
                    }
                }
            }
            //5.5- Si el modo de cuenta es autorizado
            if(MODCB.getSelectedIndex() == 2){
                //5.5.1- Que el nombre no este vacio
                if(NameAuttxt.getText().isEmpty()){
                    NameAuttxt.setBorder(borde_rojo);
                    condicion = false;
                } else {
                    NameAuttxt.setBorder(borde_default);
                }
                //5.5.2- Que la identificacion sea valida
                if(IDAuttxt.getText().isEmpty()){
                    IDAuttxt.setBorder(borde_rojo);
                    condicion = false;
                } else if(!IDAuttxt.getText().isEmpty() && (IDAuttxt.getText().length() < 7)){
                    IDAuttxt.setBorder(borde_rojo);
                    condicion = false;
                } else if(!IDAuttxt.getText().isEmpty() && !(IDAuttxt.getText().length() < 7)){
                    if(!p.comprobacionIdentificacion(IDAuttxt.getText())){
                        IDAuttxt.setBorder(borde_rojo);
                        condicion = false;
                    } else if(p.comprobacionIdentificacion(IDAuttxt.getText())){
                        IDAuttxt.setBorder(borde_default);
                    }
                }
            }
        }    
        return condicion;
    }
    
    private boolean verificacionCorreo(String email){
        boolean condicion = false;
        boolean arroba = false;
        boolean punto = false;
        for(int i = 0; i < email.length(); i++){
            char caracter = email.charAt(i);
            if(!arroba){
                if(caracter == '@'){
                    arroba = true;
                    continue;
                }
            }
            if(arroba && !punto){
                if(caracter == '.'){
                    punto = true;
                    break;
                }
            }
        }
        if(arroba && punto){
            condicion = true;
        }
        return condicion;
    }
    
    //BOTON DE CREAR PROVEEDOR
    private void CrearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBTActionPerformed
        //SE VERIFICA PRIMERO SI SE HAN RELLENADO LOS DATOS DE LOS PROVEEDORES
        if (!verificacionCompleta()) {
            JOptionPane.showMessageDialog(null, "DEBE RELLENAR LOS CAMPOS NECESARIOS \n REVISE TODOS LOS CAMPOS MARCADOS EN ROJO Y VERIFIQUE LOS ERRORES \n AYUDESE CON EL MANUAL DE USUARIO SI ES NECESARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if(verificacionCompleta()){
            //PRIMERO SE OBTIENEN TODOS LOS DATOS DE LOS CAMPOS NORMALES DEL PROVEEDOR
            int codigo = Integer.parseInt(Codigotxt.getText());
            String identificacion = IdentificacionCB.getSelectedItem().toString();
            identificacion += Identificaciontxt.getText();
            String razon_social = RazonSocialtxt.getText();
            String direccion = Direcciontxt.getText();
            String municipio = Municipiotxt.getText();
            String telefono = TipoTlftxt.getText();
            telefono += Tlftxt.getText();
            String mail = Mailtxt.getText();
            //DESPUES SE TOMA LA INFORMACION BANCARIA, PRIMERO SE INICIALIZAN LAS VARIABLES Y DESPUES SE VERIFICA SI EL USUARIO HABILITO ESTA INFORMACION
            String nombre_beneficiario = "";
            String id_beneficiario = "";
            String mail_bnf = "";
            String banco = "";
            String num_cuenta = "";
            String Tipo_cuenta = "";
            String mod_cuenta = "";
            String name_autorizado = "";
            String ID_autorizado = "";
            String MP = MPCB.getSelectedItem().toString();
            
            float MP_acordado = 0;
            if(MP.equals("ACORDADO") && !MP.isEmpty()){
                MP_acordado = Float.parseFloat(MP_Acordadotxt.getText());
            }
            
            float Cuadrilla = Float.parseFloat(Cuadrillatxt.getText()); //Float.parseFloat(String S)
            float Flete = Float.parseFloat(Fletetxt.getText());
            int Peaje = Integer.parseInt(Peajetxt.getText());
            int Cod_Tarifa = 0;         
            if(tarifa){
                Cod_Tarifa = this.cod_tarifa;
            }   
            if(BancariaBT.isSelected()){
                /*
                    SI LA INFORMACION BANCARIA ESTA HABILITADA
                    NO PUEDO PERMITIR QUE NINGUN TEXTFIELD ESTE VACIO
                */
                if(!NameBnftxt.getText().isEmpty() && !IDtxt.getText().isEmpty() && !NumCuentatxt.getText().isEmpty()){
                    
                        nombre_beneficiario = NameBnftxt.getText();
                        mail_bnf = MailBnftxt.getText();
                        banco = BancoCB.getSelectedItem().toString();
                        num_cuenta = NumCuentatxt.getText();
                        id_beneficiario = IDCB.getSelectedItem().toString();
                        id_beneficiario += IDtxt.getText();
                        Tipo_cuenta = TCuentaCB.getSelectedItem().toString();
                        mod_cuenta = MODCB.getSelectedItem().toString();
                        //PRIMERO VERIFICAMOS SI LA CUENTA ESTA EN MODO AUTORIZADA
                        if(MODCB.getSelectedItem().toString().equals("Cuenta Autorizada")){
                            //DESPUES SI QUEREMOS RECOGER ESTOS DATOS, AJURO AMBOS CAMPOS NO PUEDEN ESTAR VACIOS
                            if(!NameAuttxt.getText().isEmpty() && !IDAuttxt.getText().isEmpty()){
                                //Y ADEMAS DE ESO, DEBEMO VERIFICAR QUE LA CEDULA SEA CORRECTA
                                IDAuttxt.setBorder(borde_default);
                                name_autorizado = NameAuttxt.getText();
                                ID_autorizado = idCBaut.getSelectedItem().toString();
                                ID_autorizado += IDAuttxt.getText();   
                            } 
                        }
                }
            }
            /*============================== CREACION DEL PROVEEDOR=================================*/
            try {
                //=====================================================================================================================================================================================================================
                p.NuevoProveedor(codigo, identificacion, razon_social, direccion, municipio, telefono, mail, MP, MP_acordado, Cuadrilla, Flete, Peaje, Cod_Tarifa, tarifa);
                //Llamar a la funcion de nuevo proveedor

                if(bancaria){
                    boolean beneficiario_encontrado = b.buscarBeneficiario(id_beneficiario);
                    if(!beneficiario_encontrado){
                        b.NuevoBeneficiario(nombre_beneficiario, id_beneficiario, mail_bnf, banco, num_cuenta, Tipo_cuenta, mod_cuenta, name_autorizado, ID_autorizado);
                        int codigo_beneficiario = b.codigoSiguiente();
                        PB.crear_relacion(codigo, codigo_beneficiario);
                    } else {
                        int codigo_beneficiario2 = b.retornaCodigo(id_beneficiario);
                        PB.crear_relacion(codigo, codigo_beneficiario2);
                    }
                }
                int index = JOptionPane.showOptionDialog(null, "CREACION EXITOSA \n \n ¿DESEA CREAR UN NUEVO PROVEEDOR?", "CONFIRMACION DE CREAR", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones_confirmacionCrear, botones_confirmacionCrear[0]);
                //si desea crear nuevo
                if (index == 0) {
                    IP.setVisible(true);
                    IP.modo = 1;
                    this.dispose();
                } else {
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CreacionProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
    }//GEN-LAST:event_CrearBTActionPerformed

    private void LimpiarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTActionPerformed
        limpiar();
    }//GEN-LAST:event_LimpiarBTActionPerformed

    private void CancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarBTActionPerformed

    private void MODCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODCBActionPerformed
        if (MODCB.getSelectedItem().toString().equals("Cuenta Autorizada")) {
            NameAuttxt.setEditable(true);
            NameAuttxt.setBackground(new Color(255,255,255));
            //SE AGREGA LA ACTIVACION DEL ID COMBOBOX DEL AUTORIZADO
            idCBaut.setEnabled(true);
            IDAuttxt.setEditable(true);
            IDAuttxt.setBackground(new Color(255,255,255));
        } else if (MODCB.getSelectedItem().toString().equals("Cuenta Nueva") || MODCB.getSelectedItem().toString().equals("Cuenta Propia")) {
            NameAuttxt.setEditable(false);
            NameAuttxt.setBackground(new Color(240,240,240));
            IDAuttxt.setEditable(false);
            IDAuttxt.setBackground(new Color(240,240,240));
            idCBaut.setEnabled(false);
        }
    }//GEN-LAST:event_MODCBActionPerformed

    private void BancariaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancariaBTActionPerformed
        /*
            LO IMPORTANTE DE ESTO ES ENTENDER QUE MIENTRAS LA INFORMACION BANCARIA ESA FALSA
            NO GUARDAREMOS ESOS DATOS EN EL PROVEEDOR
        
            CUANDO SEA VERDADERA, SI LOS GUARDAREMOS
            PERO TENDREMOS QUE HACER ENTONCES VERIFICACIONES DE QUE LOS CAMPOS NO ESTEN VACIOS
        */
        if(BancariaBT.isSelected()){
            /*
                LA INFORMACION BANCARIA VIENE DE POR SI DESHABILITADA
                POR TANTO, COMO LE ESTAN PRESIONANDO EL BOTON, DEBO HABILITAR CAMPOS BANCARIOS
            */
            habilitarCamposBancarios();
            ListarBeneficiariosBT.setEnabled(true);
            bancaria = true;
            cargarDatosBeneficiarios();
        } else if(!BancariaBT.isSelected()) {
            /*
                EN ESTE MOMENTO, LA INFORMACION BANCARIA ESTABA HABILITADA
                SI LO VOLVIERON A PRESIONAR, QUIERE DECIR QUE DEBO DESHABILITAR ESOS CAMPOS
            */
            desHabilitarCamposBancarios();
            ListarBeneficiariosBT.setEnabled(false);
            bancaria = false;
        }
    }//GEN-LAST:event_BancariaBTActionPerformed

    private void PeajetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeajetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeajetxtActionPerformed

    private void MPCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPCBActionPerformed
        if(MPCB.getSelectedItem().toString().equals("ACORDADO")){
            MP_Acordadotxt.setEditable(true);
        } else {
            MP_Acordadotxt.setEditable(false);
        }
    }//GEN-LAST:event_MPCBActionPerformed

    private void TarifaEstandarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifaEstandarBTActionPerformed
        if(!TarifaEstandarBT.isSelected()){
            //PASARLO A FALSE
            //HABILITAR LOS CAMPOS
            tarifa = false;
            MPCB.setEnabled(true);
            Cuadrillatxt.setEditable(true);
            Fletetxt.setEditable(true);
        } else if(TarifaEstandarBT.isSelected()){
            //PASARLO A TRUE
            //DESHABILITAR LOS CAMPOS
            tarifa = true;
            MPCB.setSelectedIndex(0);
            MPCB.setEnabled(false);
            Cuadrillatxt.setEditable(false);
            Fletetxt.setEditable(false);
            MP_Acordadotxt.setEditable(false);
            //RE IMPRIMIR LA TARIFA
            ActualizarCamposTarifa();
        }
    }//GEN-LAST:event_TarifaEstandarBTActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void ListarBeneficiariosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBeneficiariosBTActionPerformed
        if(ListarBeneficiariosBT.getSelectedItem().toString().equals("Nuevo")){
            NameBnftxt.setText("");
            IDtxt.setText("");
            IDCB.setSelectedIndex(0);
            MailBnftxt.setText("");
            BancoCB.setSelectedIndex(0);
            NumCuentatxt.setText("");
            TCuentaCB.setSelectedIndex(0);
            MODCB.setSelectedIndex(0);
            NameAuttxt.setText("");
            idCBaut.setSelectedIndex(0);
            IDAuttxt.setText("");
            habilitarCamposBancarios();
        } else {
            int index = ListarBeneficiariosBT.getSelectedIndex();
            imprimirDatosBeneficiario(index);
            desHabilitarCamposBancarios();
        }
    }//GEN-LAST:event_ListarBeneficiariosBTActionPerformed

    private void NumCuentatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumCuentatxtKeyTyped
        if(NumCuentatxt.getText().length() >= 20){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_NumCuentatxtKeyTyped

    private void TipoTlftxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TipoTlftxtKeyTyped
        if(TipoTlftxt.getText().length() >= 4){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TipoTlftxtKeyTyped

    private void TlftxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TlftxtKeyTyped
        if(Tlftxt.getText().length() >= 7){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TlftxtKeyTyped

    private void MailBnftxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailBnftxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailBnftxtActionPerformed
    
    public void imprimirDatosBeneficiario(int index){
        index--;
        String Name_Autorizado = dataBeneficiarios[index][1].toString();
        NameBnftxt.setText(Name_Autorizado);
        
        String ID_Beneficiario = dataBeneficiarios[index][2].toString();
        char char_id = ID_Beneficiario.charAt(0);
        int index_id = p.indexIdentificacion(char_id);
        IDCB.setSelectedIndex(index_id);
        IDtxt.setText(ID_Beneficiario.substring(1, ID_Beneficiario.length()));
        
        MailBnftxt.setText(dataBeneficiarios[index][3].toString());
        BancoCB.setSelectedIndex(p.getindexBanco(dataBeneficiarios[index][4].toString()));
        NumCuentatxt.setText(dataBeneficiarios[index][5].toString());
        TCuentaCB.setSelectedIndex(p.indexTipoCuenta(dataBeneficiarios[index][6].toString()));
        MODCB.setSelectedIndex(p.indexmod_Cuenta(dataBeneficiarios[index][7].toString()));
        if(dataBeneficiarios[index][7].toString().equals("Cuenta Autorizada")){
            NameAuttxt.setText(dataBeneficiarios[index][8].toString());
            String ID_autorizado = dataBeneficiarios[index][9].toString();
            System.out.println(ID_autorizado);
            char char_autorizado = ID_autorizado.charAt(0);
            int index_autorizado = p.indexIdentificacion(char_autorizado);
            idCBaut.setSelectedIndex(index_autorizado);
            IDAuttxt.setText(ID_autorizado.substring(1, ID_autorizado.length()));
        } else {
            idCBaut.setSelectedIndex(0);
            IDAuttxt.setText("");
            NameAuttxt.setText("");
        }

    }
    
    public void habilitarCamposBancarios(){
        NameBnftxt.setEditable(true);
        IDtxt.setEditable(true);
        IDCB.setEnabled(true);
        MailBnftxt.setEditable(true);
        BancoCB.setEnabled(true);
        NumCuentatxt.setEditable(true);
        TCuentaCB.setEnabled(true);
        MODCB.setEnabled(true);
        if(MODCB.getSelectedItem().toString().equals("Cuenta Autorizada")){
            NameAuttxt.setEditable(true);
            idCBaut.setEnabled(true);
            IDAuttxt.setEditable(true);
        }
    }
    
    public void desHabilitarCamposBancarios(){
        NameBnftxt.setEditable(false);
        IDtxt.setEditable(false);
        IDCB.setEnabled(false);
        MailBnftxt.setEditable(false);
        BancoCB.setEnabled(false);
        NumCuentatxt.setEditable(false);
        TCuentaCB.setEnabled(false);
        MODCB.setEnabled(false);
        NameAuttxt.setEditable(false);
        idCBaut.setEnabled(false);
        IDAuttxt.setEditable(false);
    }
    
    public void limpiar() {
        RazonSocialtxt.setText("");
        Direcciontxt.setText("");
        Municipiotxt.setText("");
        Tlftxt.setText("");
        TipoTlftxt.setText("");
        Mailtxt.setText("");
        NameBnftxt.setText("");
        IDCB.setSelectedIndex(0);
        IDtxt.setText("");
        MailBnftxt.setText("");
        BancoCB.setSelectedIndex(0);
        NumCuentatxt.setText("");
        TCuentaCB.setSelectedIndex(0);
        MODCB.setSelectedIndex(0);
        NameAuttxt.setText("");
        IDAuttxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionProveedor().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertaNumCuenta;
    private javax.swing.JToggleButton BancariaBT;
    private javax.swing.JComboBox<String> BancoCB;
    private javax.swing.JLabel BancoL;
    private javax.swing.JButton CancelarBT;
    private javax.swing.JLabel CodigoL;
    private javax.swing.JTextField Codigotxt;
    private javax.swing.JButton CrearBT;
    private javax.swing.JTextField Cuadrillatxt;
    private javax.swing.JLabel DireccionL;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JTextField Fletetxt;
    private javax.swing.JLabel FotoIdentificacionv;
    private javax.swing.JLabel IDAutL;
    private javax.swing.JTextField IDAuttxt;
    private javax.swing.JComboBox<String> IDCB;
    private javax.swing.JLabel IDL;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JComboBox<String> IdentificacionCB;
    private javax.swing.JLabel IdentificacionL;
    private javax.swing.JLabel IdentificacionProveedor;
    private javax.swing.JLabel IdentificacionProveedor1;
    private javax.swing.JLabel IdentificacionProveedor2;
    private javax.swing.JLabel IdentificacionProveedor3;
    private javax.swing.JLabel IdentificacionProveedor4;
    private javax.swing.JLabel IdentificacionProveedor5;
    private javax.swing.JLabel IdentificacionProveedor6;
    private javax.swing.JTextField Identificaciontxt;
    private javax.swing.JLabel InformacionBancariaL;
    private javax.swing.JButton LimpiarBT;
    private javax.swing.JComboBox<String> ListarBeneficiariosBT;
    private javax.swing.JLabel LogoInformacionBancaria;
    private javax.swing.JComboBox<String> MODCB;
    private javax.swing.JLabel MODL;
    private javax.swing.JComboBox<String> MPCB;
    private javax.swing.JTextField MP_Acordadotxt;
    private javax.swing.JLabel MailBnfL;
    private javax.swing.JTextField MailBnftxt;
    private javax.swing.JLabel MailL;
    private javax.swing.JTextField Mailtxt;
    private javax.swing.JLabel MunicipioLB;
    private javax.swing.JTextField Municipiotxt;
    private javax.swing.JLabel NameAutL;
    private javax.swing.JTextField NameAuttxt;
    private javax.swing.JLabel NameBnfL;
    private javax.swing.JTextField NameBnftxt;
    private javax.swing.JLabel NumCuentaL;
    private javax.swing.JTextField NumCuentatxt;
    private javax.swing.JPanel PanelBancario;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelDeIdentificacion;
    private javax.swing.JPanel PanelDePagos;
    private javax.swing.JTextField Peajetxt;
    private javax.swing.JLabel RazonSocialL;
    private javax.swing.JTextField RazonSocialtxt;
    private javax.swing.JComboBox<String> TCuentaCB;
    private javax.swing.JLabel TCuentaL;
    private javax.swing.JToggleButton TarifaEstandarBT;
    private javax.swing.JTextField TipoTlftxt;
    private javax.swing.JLabel TlfL;
    private javax.swing.JTextField Tlftxt;
    private javax.swing.JComboBox<String> idCBaut;
    // End of variables declaration//GEN-END:variables
}
