/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.proveedores;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import logica.proveedor;

/**
 *
 * @author DANIEL
 */
public class TablaProveedores extends javax.swing.JFrame {

    public int modo;
    public proveedor p;
    public TablaProveedores() {
        initComponents();
        p = new proveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        CodigoLB = new javax.swing.JLabel();
        Identificaciontxt = new javax.swing.JTextField();
        CodigoLB1 = new javax.swing.JLabel();
        IdentificacionCB = new javax.swing.JComboBox<>();
        Codigotxt = new javax.swing.JTextField();
        RazonSocialLB = new javax.swing.JLabel();
        RazonSocialtxt = new javax.swing.JTextField();
        CodigoLB3 = new javax.swing.JLabel();
        Direcciontxt = new javax.swing.JTextField();
        CodigoLB4 = new javax.swing.JLabel();
        Municipiotxt = new javax.swing.JTextField();
        CodigoLB5 = new javax.swing.JLabel();
        TLFtxt = new javax.swing.JTextField();
        TLF2txt = new javax.swing.JTextField();
        CodigoLB6 = new javax.swing.JLabel();
        Correotxt = new javax.swing.JTextField();
        CodigoLB7 = new javax.swing.JLabel();
        NameBnftxt = new javax.swing.JTextField();
        CodigoLB8 = new javax.swing.JLabel();
        IDbnfCB = new javax.swing.JComboBox<>();
        IDBnfTxt = new javax.swing.JTextField();
        CodigoLB9 = new javax.swing.JLabel();
        CorreoBnfTxt = new javax.swing.JTextField();
        EntidadBancariaCB = new javax.swing.JComboBox<>();
        CodigoLB10 = new javax.swing.JLabel();
        CodigoLB11 = new javax.swing.JLabel();
        NumCuentatxt = new javax.swing.JTextField();
        TCuentaL = new javax.swing.JLabel();
        TipoCuentaCB = new javax.swing.JComboBox<>();
        MODL = new javax.swing.JLabel();
        MODCB = new javax.swing.JComboBox<>();
        MODL1 = new javax.swing.JLabel();
        MonedaCB = new javax.swing.JComboBox<>();
        NameAutL = new javax.swing.JLabel();
        NameAuttxt = new javax.swing.JTextField();
        IDAutL = new javax.swing.JLabel();
        IDAutCB = new javax.swing.JComboBox<>();
        IDAutorizadoTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Identificacion", "Razon Social", "Direccion", "Municipio", "Telefono", "Email", "Nombre de Beneficiario", "Cedula Beneficiario", "Correo Beneficiario", "Entidad Bancaria", "Numero de Cuenta", "Tipo de cuenta", "Modo de cuenta", "Moneda", "Nombre autorizado", "Cedula autorizado", "Estado Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabla);

        CodigoLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB.setText("Codigo");

        Identificaciontxt.setEditable(false);
        Identificaciontxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB1.setText("Identificacion");

        IdentificacionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IdentificacionCB.setEnabled(false);

        Codigotxt.setEditable(false);
        Codigotxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        RazonSocialLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RazonSocialLB.setText("Razon Social");

        RazonSocialtxt.setEditable(false);
        RazonSocialtxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB3.setText("Direccion");

        Direcciontxt.setEditable(false);
        Direcciontxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB4.setText("Municipio");

        Municipiotxt.setEditable(false);
        Municipiotxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB5.setText("Telefono");

        TLFtxt.setEditable(false);
        TLFtxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TLF2txt.setEditable(false);
        TLF2txt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB6.setText("Correo");

        Correotxt.setEditable(false);
        Correotxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB7.setText("Nombre de Beneficiario");

        NameBnftxt.setEditable(false);
        NameBnftxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB8.setText("Identificacion de Beneficiario");

        IDbnfCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IDbnfCB.setEnabled(false);

        IDBnfTxt.setEditable(false);
        IDBnfTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CodigoLB9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB9.setText("Correo de Beneficiario");

        CorreoBnfTxt.setEditable(false);
        CorreoBnfTxt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        EntidadBancariaCB.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        EntidadBancariaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MERCANTIL BANCO UNIVERSAL", "BANCO DE VENEZUELA S.A BANCO UNIVERSAL", "VENEZOLANO DE CREDITO S.A BANCO UNIVERSAL", "BANCO PROVINCIAL S.A BANCO UNIVERSAL", "BANCO DEL CARIBE S.A C.A", "BANCO EXTERIOR S.A", "BANCO OCCIDENTAL DE DESCUENTO S.A C.A", "BANCO CARONI C.A BANCO UNIVERSAL", "BANESCO BANCO UNIVERSAL", "BANCO SOFITASA", "BANCO PLAZA", "BANCO DE COMERCIO EXTERIOR", "FONDO COMUN C.A BANCO UNIVERSAL", "100% BANCO, BANCO UNIVERSAL C.A", "DEL SUR BANCO UNIVERSAL, C.A", "BANCO DEL TESORO ", "BANCO AGRICOLA DE VENEZUELA C.A", "BANCRECER S.A BANCO MICROFINANCIERO", "MIBANCO BANCO DE DESARROLLO", "BANCO ACTIVO C.A", "BANCA AMIGA BANCO MICROFINANCIERO", "BANCO BICENTENARIO BANCO UNIVERSAL C.A", "BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA", "BANCO NACIONAL DE CREDITO " }));
        EntidadBancariaCB.setEnabled(false);

        CodigoLB10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB10.setText("Numero de Cuenta");

        CodigoLB11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodigoLB11.setText("Entidad Bancaria");

        NumCuentatxt.setEditable(false);
        NumCuentatxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        TCuentaL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TCuentaL.setText("Tipo de cuenta");

        TipoCuentaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente", "Cuenta Maxima", "Cuenta Moneda Extranjera" }));
        TipoCuentaCB.setEnabled(false);

        MODL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MODL.setText("MOD (*)");

        MODCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Propia", "Cuenta Nueva", "Cuenta Autorizada" }));
        MODCB.setEnabled(false);
        MODCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODCBActionPerformed(evt);
            }
        });

        MODL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MODL1.setText("Moneda");

        MonedaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "$" }));
        MonedaCB.setEnabled(false);

        NameAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NameAutL.setText("Nombre del Autorizado (*)");

        NameAuttxt.setEditable(false);
        NameAuttxt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        IDAutL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IDAutL.setText("Identificación del Autorizado (*)");

        IDAutCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "P", "G" }));
        IDAutCB.setEnabled(false);

        IDAutorizadoTXT.setEditable(false);
        IDAutorizadoTXT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("CERRAR");

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("SELECCIONAR");
        jButton2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodigoLB)
                                .addGap(21, 21, 21)
                                .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addComponent(CodigoLB1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodigoLB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Direcciontxt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RazonSocialLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RazonSocialtxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodigoLB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Municipiotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CodigoLB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TLFtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TLF2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodigoLB6)
                        .addGap(22, 22, 22)
                        .addComponent(Correotxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodigoLB7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameBnftxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CodigoLB8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDbnfCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDBnfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoLB9)
                            .addComponent(CodigoLB10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumCuentatxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCuentaL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipoCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MODL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CorreoBnfTxt)
                                .addGap(18, 18, 18)
                                .addComponent(CodigoLB11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EntidadBancariaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MODL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameAutL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameAuttxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDAutL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDAutCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDAutorizadoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLB)
                    .addComponent(Identificaciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLB1)
                    .addComponent(IdentificacionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RazonSocialLB)
                    .addComponent(RazonSocialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLB3)
                    .addComponent(Direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLB4)
                    .addComponent(Municipiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLB5)
                    .addComponent(TLFtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TLF2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLB6)
                    .addComponent(Correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameBnftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLB7)
                    .addComponent(CodigoLB8)
                    .addComponent(IDbnfCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDBnfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLB9)
                    .addComponent(CorreoBnfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntidadBancariaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLB11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLB10)
                    .addComponent(NumCuentatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCuentaL)
                    .addComponent(TipoCuentaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MODL)
                    .addComponent(MODCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MODL1)
                    .addComponent(MonedaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameAutL)
                    .addComponent(NameAuttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDAutL)
                    .addComponent(IDAutCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDAutorizadoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MODCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODCBActionPerformed
       
    }//GEN-LAST:event_MODCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(modo == 0){
            mostrarTodos();
        }
    }//GEN-LAST:event_formWindowOpened
    
    public void mostrarTodos(){
        //Objeto para almacenar datos;
        Object[][] data;
        String[] columNames = {"Codigo", "Identificacion", "Razon Social", "Direccion", "Municipio", "Telefono", "Email", "Nombre de Beneficiario", "Cedula Beneficiario", "Correo Beneficiario", "Entidad Bancaria", "Numero Cuenta", "Tipo de Cuenta", "Modo de Cuenta", "Moneda", "Nombre Autorizado" , "Cedula Autorizado", "Estado"};
        try {
            //se utiliza la funcion
            data = p.getDatos();
            DefaultTableModel datos = new DefaultTableModel(data, columNames);
            tabla.setModel(datos);
        } catch (SQLException ex) {
            Logger.getLogger(TablaProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoLB;
    private javax.swing.JLabel CodigoLB1;
    private javax.swing.JLabel CodigoLB10;
    private javax.swing.JLabel CodigoLB11;
    private javax.swing.JLabel CodigoLB3;
    private javax.swing.JLabel CodigoLB4;
    private javax.swing.JLabel CodigoLB5;
    private javax.swing.JLabel CodigoLB6;
    private javax.swing.JLabel CodigoLB7;
    private javax.swing.JLabel CodigoLB8;
    private javax.swing.JLabel CodigoLB9;
    private javax.swing.JTextField Codigotxt;
    private javax.swing.JTextField CorreoBnfTxt;
    private javax.swing.JTextField Correotxt;
    private javax.swing.JTextField Direcciontxt;
    private javax.swing.JComboBox<String> EntidadBancariaCB;
    private javax.swing.JComboBox<String> IDAutCB;
    private javax.swing.JLabel IDAutL;
    private javax.swing.JTextField IDAutorizadoTXT;
    private javax.swing.JTextField IDBnfTxt;
    private javax.swing.JComboBox<String> IDbnfCB;
    private javax.swing.JComboBox<String> IdentificacionCB;
    private javax.swing.JTextField Identificaciontxt;
    private javax.swing.JComboBox<String> MODCB;
    private javax.swing.JLabel MODL;
    private javax.swing.JLabel MODL1;
    private javax.swing.JComboBox<String> MonedaCB;
    private javax.swing.JTextField Municipiotxt;
    private javax.swing.JLabel NameAutL;
    private javax.swing.JTextField NameAuttxt;
    private javax.swing.JTextField NameBnftxt;
    private javax.swing.JTextField NumCuentatxt;
    private javax.swing.JLabel RazonSocialLB;
    private javax.swing.JTextField RazonSocialtxt;
    private javax.swing.JLabel TCuentaL;
    private javax.swing.JTextField TLF2txt;
    private javax.swing.JTextField TLFtxt;
    private javax.swing.JComboBox<String> TipoCuentaCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
