/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.boletos;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import logica.Tasa_Precios;
import logica.boleto;

/**
 *
 * @author DANIEL
 */
public class CreacionBoleto extends javax.swing.JFrame {

    /**
     * Creates new form CreacionBoleto
     */
    public String Num_Boleto;
    public String[] botones_confirmacionCrear = {"SI", "NO"};
    public boleto boleto = new boleto();
    public IdentificacionBoleto IB = new IdentificacionBoleto();
    private Border borde_rojo = BorderFactory.createLineBorder(Color.RED, 1);
    private Border borde_default;
    private Tasa_Precios TP = new Tasa_Precios();
    public CreacionBoleto() {
        initComponents();
        borde_default = NumBoletotxt.getBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumBoletotxt = new javax.swing.JTextField();
        NumBoletoLB = new javax.swing.JLabel();
        FechaLB = new javax.swing.JLabel();
        Fechatxt = new javax.swing.JTextField();
        SemanaLB = new javax.swing.JLabel();
        Semanatxt = new javax.swing.JTextField();
        KgBrutosLB = new javax.swing.JLabel();
        KgBrutostxt = new javax.swing.JTextField();
        KgNetosLB = new javax.swing.JLabel();
        KgNetostxt = new javax.swing.JTextField();
        MsLB = new javax.swing.JLabel();
        MStxt = new javax.swing.JTextField();
        ImpurezasLB = new javax.swing.JLabel();
        Impurezastxt = new javax.swing.JTextField();
        ObservacionesLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacionestTXT = new javax.swing.JTextArea();
        CancelarBT = new javax.swing.JButton();
        CrearBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Nombretxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boleto.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Informacion del Boleto");

        NumBoletotxt.setEditable(false);

        NumBoletoLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NumBoletoLB.setText("Num. Boleto");

        FechaLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        FechaLB.setText("Fecha");

        Fechatxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                FechatxtFocusLost(evt);
            }
        });

        SemanaLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SemanaLB.setText("Semana");

        Semanatxt.setEditable(false);

        KgBrutosLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        KgBrutosLB.setText("Kg. Brutos");

        KgNetosLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        KgNetosLB.setText("Kg. Netos");

        MsLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MsLB.setText("%MS");

        ImpurezasLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ImpurezasLB.setText("Impurezas");

        ObservacionesLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ObservacionesLB.setText("Observaciones");

        ObservacionestTXT.setColumns(20);
        ObservacionestTXT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ObservacionestTXT.setRows(5);
        jScrollPane1.setViewportView(ObservacionestTXT);

        CancelarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelarBT.setText("CANCELAR");
        CancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTActionPerformed(evt);
            }
        });

        CrearBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CrearBT.setText("CREAR");
        CrearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumBoletoLB)
                                    .addComponent(FechaLB)
                                    .addComponent(KgBrutosLB))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(NumBoletotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(Fechatxt))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(SemanaLB))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Semanatxt)
                                            .addComponent(Nombretxt)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(KgBrutostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KgNetosLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KgNetostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MsLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MStxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ImpurezasLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Impurezastxt, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ObservacionesLB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CrearBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelarBT)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumBoletotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumBoletoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaLB)
                            .addComponent(Fechatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SemanaLB)
                            .addComponent(Semanatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KgBrutosLB)
                            .addComponent(KgBrutostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KgNetosLB)
                            .addComponent(KgNetostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MsLB)
                            .addComponent(MStxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImpurezasLB)
                            .addComponent(Impurezastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ObservacionesLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBT)
                    .addComponent(CrearBT))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificacionCompleta(){
        boolean condicion = true;
        /*
            AQUI SE TIENEN QUE VERIFICAR LAS SIGUIENTES COSAS:
            1- Nombre no vacio.
            2- Fecha no vacia. (La validacion del formato ya se encuentra a parte)
            3- Todos los montos ingresados y en su correspondiente formato.
        */
        //1- Nombre no vacio.
        if(Nombretxt.getText().isEmpty()){
            Nombretxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Nombretxt.getText().isEmpty()){
            Nombretxt.setBorder(borde_default);
        }
        //2- Fecha no vacia.
        if(Fechatxt.getText().isEmpty()){
            Fechatxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Fechatxt.getText().isEmpty()){
            Fechatxt.setBorder(borde_default);
        }
        //3- Todos los montos ingresados y en su correspondiente formato.
        //3.1- Kg. Brutos
        if(KgBrutostxt.getText().isEmpty()){
            KgBrutostxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!KgBrutostxt.getText().isEmpty()){
            if(!boleto.comprobacionFlotante(KgBrutostxt.getText())){
                KgBrutostxt.setBorder(borde_rojo);
                condicion = false;
            } else if(boleto.comprobacionFlotante(KgBrutostxt.getText())){
                KgBrutostxt.setBorder(borde_default);
            }
        }
        //3.2- Kg. Netos
        if(KgNetostxt.getText().isEmpty()){
            KgNetostxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!KgNetostxt.getText().isEmpty()){
            if(!boleto.comprobacionFlotante(KgNetostxt.getText())){
                KgNetostxt.setBorder(borde_rojo);
                condicion = false;
            } else if(boleto.comprobacionFlotante(KgNetostxt.getText())){
                KgNetostxt.setBorder(borde_default);
            }
        }
        //3.3- Materia Seca
        if(MStxt.getText().isEmpty()){
            MStxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!MStxt.getText().isEmpty()){
            if(!boleto.comprobacionEntero(MStxt.getText())){
                MStxt.setBorder(borde_rojo);
                condicion = false;
            } else if(boleto.comprobacionEntero(MStxt.getText())){
                if(TP.encontrarMS(Integer.parseInt(MStxt.getText()))){
                    MStxt.setBorder(borde_default);
                } else if(!TP.encontrarMS(Integer.parseInt(MStxt.getText()))){
                    MStxt.setBorder(borde_rojo);
                    condicion = false;
                    JOptionPane.showMessageDialog(null, "LA MATERIA SECA QUE USTED INGRESÓ NO SE ENCUENTRA EN LA TASA DE PRECIOS DEL SISTEMA", "MATERIA SECA NO ENCONTRADA", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        //3.4- Impurezas
        if(Impurezastxt.getText().isEmpty()){
            Impurezastxt.setBorder(borde_rojo);
            condicion = false;
        } else if(!Impurezastxt.getText().isEmpty()){
            if(!boleto.comprobacionEntero(Impurezastxt.getText())){
                Impurezastxt.setBorder(borde_rojo);
                condicion = false;
            } else if(boleto.comprobacionEntero(Impurezastxt.getText())){
                Impurezastxt.setBorder(borde_default);
            }
        }
        return condicion;
    }
    
    private void CancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTActionPerformed
        String[] botones_confirmacionCancelar = {"NO, NO DESEO CANCELAR", "SI, SI DESEO CANCELAR"};
        int index = JOptionPane.showOptionDialog(null, "DESEA CANCELAR LA CREACION DE TRANSACCION?", "CONFIRMACION DE CANCELACION", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones_confirmacionCancelar, botones_confirmacionCancelar[0]);
        /*
            ESTE AVISO ARROJA DOS VALORES ENTEROS
            0- NO DESEA CANCELAR
            1- SI DESEA CANCELAR
         */
        if (index == 1) {
            this.dispose();
        }
        
    }//GEN-LAST:event_CancelarBTActionPerformed

    private void CrearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBTActionPerformed
        if(verificacionCompleta()){
            /*
                TENEMOS QUE IDENTIFICAR PRIMERO QUE TODOS LOS DATOS HAYAN SIDO COMPLETADOS (excepto las observaciones)
                GUARDAMOS EN VARIAS VARIABLES LOS DATOS
            */
            String num_boleto = NumBoletotxt.getText();
            String nombre = Nombretxt.getText();
            String Fecha = Fechatxt.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat output = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date data;
            String dateFinal = "";
            try {
                data = sdf.parse(Fecha);
                dateFinal = output.format(data);
            } catch (ParseException ex) {
                Logger.getLogger(CreacionBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
            String Semana = Semanatxt.getText();
            float Kg_Brutos = Float.parseFloat(KgBrutostxt.getText());
            float Kg_Netos = Float.parseFloat(KgNetostxt.getText());
            int MS = Integer.parseInt(MStxt.getText());
            int impurezas = Integer.parseInt(Impurezastxt.getText());
            String observaciones = ObservacionestTXT.getText();

            if(!num_boleto.isEmpty() && !Fecha.isEmpty() && !nombre.isEmpty() && !Semana.isEmpty() && !KgBrutostxt.getText().isEmpty() 
                    && !KgNetostxt.getText().isEmpty() && !MStxt.getText().isEmpty() && !Impurezastxt.getText().isEmpty()){

                try {
                    /*
                    ESTO SIGNIFICA QUE TODOS Y ABSOLUTAMENTE TODOS ESTAN LLENOS
                    COMO YA TENEMOS LOS DATOS AQUI, SOLAMENTE PROCEDEMOS A LLAMAR A LA FUNCION CON LAS VARIABLES
                    */
                    boleto.NuevoBoleto(num_boleto, nombre, dateFinal, Semana, Kg_Brutos, Kg_Netos, MS, impurezas, 0, observaciones);
                    // EL ULTIMO DATO DEL BOLETO ES 0, QUE SIGNIFICA LA CANTIDAD DE TRANSACCIONES
                    // COMO ESTE BOLETO, ESTA CREANDOSE A PENAS, NO TIENE NIGUNA TRANSACCION
                    int index = JOptionPane.showOptionDialog(null, "CREACION EXITOSA \n \n ¿DESEA CREAR UN NUEVO BOLETO?", "CONFIRMACION DE CREAR", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botones_confirmacionCrear, botones_confirmacionCrear[0]);
                    if(index == 0){
                        IB.setVisible(true);
                        this.dispose();
                    } else {
                        this.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(CreacionBoleto.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS CAMPOS NECESARIOS EN EL FORMATO CORRESPONDIENTE \nDE SER NECESARIO AYUDESE DEL MANUAL DE USUARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS CAMPOS NECESARIOS EN EL FORMATO CORRESPONDIENTE \nDE SER NECESARIO AYUDESE DEL MANUAL DE USUARIO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearBTActionPerformed

    private void FechatxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FechatxtFocusLost
        if(Fechatxt.getText().length() == 10){
            String date2 = Fechatxt.getText();
            Date anio = new Date();
            SimpleDateFormat formatoAnio = new SimpleDateFormat("YYYY");
            String anioActual = formatoAnio.format(anio);
            try {
                Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(date2);
                Calendar calendar = new GregorianCalendar();
                calendar.setTime(date1);
                Semanatxt.setText((calendar.get(Calendar.WEEK_OF_YEAR) - 1) + "-" + anioActual);
                Fechatxt.setBorder(borde_default);
            } catch (ParseException ex) {
                Fechatxt.setBorder(borde_rojo);
                JOptionPane.showMessageDialog(null, "INGRESE LA FECHA EN EL FORMATO CORRESPONDIENTE: DD/MM/YYYY", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Fechatxt.setBorder(borde_rojo);
            JOptionPane.showMessageDialog(null, "INGRESE LA FECHA EN EL FORMATO CORRESPONDIENTE: DD/MM/YYYY", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FechatxtFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NumBoletotxt.setText(Num_Boleto);
    }//GEN-LAST:event_formWindowOpened
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBT;
    private javax.swing.JButton CrearBT;
    private javax.swing.JLabel FechaLB;
    private javax.swing.JTextField Fechatxt;
    private javax.swing.JLabel ImpurezasLB;
    private javax.swing.JTextField Impurezastxt;
    private javax.swing.JLabel KgBrutosLB;
    private javax.swing.JTextField KgBrutostxt;
    private javax.swing.JLabel KgNetosLB;
    private javax.swing.JTextField KgNetostxt;
    private javax.swing.JTextField MStxt;
    private javax.swing.JLabel MsLB;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JLabel NumBoletoLB;
    private javax.swing.JTextField NumBoletotxt;
    private javax.swing.JLabel ObservacionesLB;
    private javax.swing.JTextArea ObservacionestTXT;
    private javax.swing.JLabel SemanaLB;
    private javax.swing.JTextField Semanatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
