/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.Tasas_USD;

import clases.anticipos.CrearAnticipo;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Tasa_USD;
import logica.boleto;

/**
 *
 * @author usuario
 */
public class TasaBsUSD extends javax.swing.JFrame {

    private int fila = -1;
    private Object[][] dataTasas;
    private Tasa_USD tasaObjeto = new Tasa_USD();
    public boolean seleccionado = false;
    public TasaBsUSD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        CancelarBT = new javax.swing.JButton();
        AgregarBT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CodTazaLB = new javax.swing.JLabel();
        CodTazatxt = new javax.swing.JTextField();
        DiaLB = new javax.swing.JLabel();
        DiaTXT = new javax.swing.JTextField();
        SemanaLB = new javax.swing.JLabel();
        Semanatxt = new javax.swing.JTextField();
        montoLB = new javax.swing.JLabel();
        Montotxt = new javax.swing.JTextField();
        SeleccionarBT = new javax.swing.JToggleButton();
        CambiatMontoBT = new javax.swing.JToggleButton();
        NuevaTazaBT = new javax.swing.JToggleButton();
        Limpiarbt = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabla.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Desde", "Hasta", ""
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        CancelarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CancelarBT.setText("Cancelar");
        CancelarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTActionPerformed(evt);
            }
        });

        AgregarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AgregarBT.setText("Agregar");
        AgregarBT.setEnabled(false);
        AgregarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBTActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollarmini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Informacion de la Tasa");

        CodTazaLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CodTazaLB.setText("Identificador de la Tasa");

        CodTazatxt.setEditable(false);

        DiaLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DiaLB.setText("Dia");

        DiaTXT.setEditable(false);
        DiaTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DiaTXTFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                DiaTXTFocusGained(evt);
            }
        });
        DiaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaTXTActionPerformed(evt);
            }
        });

        SemanaLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SemanaLB.setText("Semana");

        Semanatxt.setEditable(false);

        montoLB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        montoLB.setText("Monto");

        Montotxt.setEditable(false);

        SeleccionarBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SeleccionarBT.setText("Seleccionar");
        SeleccionarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarBTActionPerformed(evt);
            }
        });

        CambiatMontoBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CambiatMontoBT.setText("Cambiar Monto");
        CambiatMontoBT.setEnabled(false);
        CambiatMontoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiatMontoBTActionPerformed(evt);
            }
        });

        NuevaTazaBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NuevaTazaBT.setText("Nueva Tasa");
        NuevaTazaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaTazaBTActionPerformed(evt);
            }
        });

        Limpiarbt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Limpiarbt.setText("Limpiar");
        Limpiarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CodTazaLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CodTazatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(montoLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Montotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiaLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(165, 165, 165))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SemanaLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Semanatxt)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DiaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Limpiarbt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CambiatMontoBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NuevaTazaBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgregarBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeleccionarBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarBT)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Limpiarbt))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodTazaLB)
                            .addComponent(CodTazatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiaLB)
                            .addComponent(DiaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SemanaLB)
                            .addComponent(Semanatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(montoLB)
                            .addComponent(Montotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBT)
                    .addComponent(AgregarBT)
                    .addComponent(SeleccionarBT)
                    .addComponent(NuevaTazaBT)
                    .addComponent(CambiatMontoBT))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mostrarTodos();
    }//GEN-LAST:event_formWindowOpened

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        fila = tabla.rowAtPoint(evt.getPoint());
        if(fila > -1 && seleccionado == false){
           CodTazatxt.setText(String.valueOf(tabla.getValueAt(fila, 0)));
           DiaTXT.setText(String.valueOf(tabla.getValueAt(fila, 1)));
           Semanatxt.setText(String.valueOf(tabla.getValueAt(fila, 2)));
           Montotxt.setText(String.valueOf(tabla.getValueAt(fila, 3)));

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void CambiatMontoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiatMontoBTActionPerformed
        if(seleccionado){
         AgregarBT.setEnabled(true);
         NuevaTazaBT.setEnabled(false);
         Montotxt.setEditable(true);
        }else{
          JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER SELECIONADO UNA TASA A MODIFICAR", "ERROR", JOptionPane.ERROR_MESSAGE);
          CambiatMontoBT.setSelected(false);
          AgregarBT.setEnabled(false);
          
        }
        if(!CambiatMontoBT.isSelected()){
          AgregarBT.setEnabled(false);
          NuevaTazaBT.setEnabled(true);
          Montotxt.setEditable(false);
        }
       
    }//GEN-LAST:event_CambiatMontoBTActionPerformed

    private void NuevaTazaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaTazaBTActionPerformed
       CambiatMontoBT.setEnabled(false);
       AgregarBT.setEnabled(true);
       SeleccionarBT.setEnabled(false);
       int codigo = 0;
       if(!SeleccionarBT.isSelected() && CodTazatxt.getText().isEmpty()){
           DiaTXT.setEditable(true);
           DiaTXT.setText("DD/MM/YYYY");
           Montotxt.setEditable(true);
           try {
               codigo = tasaObjeto.codigoSiguiente();
               CodTazatxt.setText(String.valueOf(codigo));
           } catch (Exception ex) {
               Logger.getLogger(TasaBsUSD.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
       }else{
           JOptionPane.showMessageDialog(null, "ASEGURESE DE NO TENER NINGUNA TASA SELECCIONADA PARA AGREGAR UNA NUEVA", "ERROR", JOptionPane.ERROR_MESSAGE);
           NuevaTazaBT.setSelected(false);
       }
           
       if(!NuevaTazaBT.isSelected()){
           CambiatMontoBT.setEnabled(true);
           Montotxt.setEditable(false);
           AgregarBT.setEnabled(false);
           SeleccionarBT.setEnabled(true);
       }
        
    }//GEN-LAST:event_NuevaTazaBTActionPerformed

    private void SeleccionarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarBTActionPerformed
        if(!CodTazatxt.getText().isEmpty() && SeleccionarBT.isSelected()){
            tabla.setVisible(false);
            seleccionado = true;
            CambiatMontoBT.setEnabled(true);
            NuevaTazaBT.setEnabled(false);
        }else if(CambiatMontoBT.isSelected()){
            JOptionPane.showMessageDialog(null, "TIENE LA OPCION DE HABILITAR EDICION ACTIVADA, DESACTIVELA PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            SeleccionarBT.setSelected(true);
        }else  if(NuevaTazaBT.isSelected()){
            JOptionPane.showMessageDialog(null, "TIENE LA OPCION DE HABILITAR CREACION ACTIVADA, DESACTIVELA PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            SeleccionarBT.setSelected(false);
        }else if(CodTazatxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "SELECCIONE UN ELEMENTO DE LA TABLA", "ERROR", JOptionPane.ERROR_MESSAGE);
            SeleccionarBT.setSelected(false);
        }else if(!SeleccionarBT.isSelected()){
            tabla.setVisible(true);
            seleccionado = false;
            CambiatMontoBT.setEnabled(false);
            NuevaTazaBT.setEnabled(true);
        }    
    }//GEN-LAST:event_SeleccionarBTActionPerformed

    private void DiaTXTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaTXTFocusGained
        if(NuevaTazaBT.isSelected()){
            String fecha = DiaTXT.getText();
            char letra = fecha.charAt(0);
            if (letra == 'D'){
            DiaTXT.setText("");
            }
        }
       
    }//GEN-LAST:event_DiaTXTFocusGained

    private void DiaTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaTXTFocusLost
        if(NuevaTazaBT.isSelected()){
            String fecha = DiaTXT.getText();
            if (DiaTXT.getText().isEmpty()){ 
                DiaTXT.setText("DD/MM/YYYY");
            } else {
                Date anio = new Date();
                SimpleDateFormat formatoAnio = new SimpleDateFormat("YYYY");
                String anioActual = formatoAnio.format(anio);
                try{
                    Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(fecha);
                    Calendar calendar = new GregorianCalendar();
                    calendar.setTime(date1);
                    Semanatxt.setText((calendar.get(Calendar.WEEK_OF_YEAR) - 1) + "-" + anioActual);
                }catch(ParseException ex){
                    JOptionPane.showMessageDialog(null, "INGRESE LA FECHA EN EL FORMATO CORRESPONDIENTE: DD/MM/YYYY", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_DiaTXTFocusLost

    public void mostrarTodos(){
        Object [][] datatabla;
        String[] columName = {"Codigo", "fechaI", "semana", "monto"};
        try{
            datatabla = tasaObjeto.getDatos();
            DefaultTableModel datos = new DefaultTableModel(datatabla,columName);
            tabla.setModel(datos);
        }catch(SQLException ex){
            Logger.getLogger(TasaBsUSD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void updateTabla(){
        String[] columName = {"Codigo", "fechaI", "semana", "monto"};
        try {
            dataTasas = tasaObjeto.getDatos();
            DefaultTableModel datos = new DefaultTableModel(dataTasas, columName);
            tabla.setModel(datos);
        } catch (SQLException ex) {
            Logger.getLogger(TasaBsUSD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void AgregarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBTActionPerformed
        if(CambiatMontoBT.isSelected()){
            //SE AGREGA ALERTA DE GUARDADO + OPCION YES/NO
            int resp = JOptionPane.showConfirmDialog(null, "SE VA A PROCEDER A MODIFICAR EL MONTO\n"+"¿ESTA SEGURO?",
            "MODIFICACION DE MONTO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE/*El tipo de ventana, en este caso WARNING*/);
             //SI LA RESPUESTA ES "YES"
            if(resp == JOptionPane.YES_OPTION){
              //VERIFICAR SI LOS CAMPOS ESTAN VACIOS
                if(!Montotxt.getText().isEmpty()){
                   int codigo = Integer.parseInt(CodTazatxt.getText());
                   double monto = Double.parseDouble(Montotxt.getText());
                   tasaObjeto.UpdateTasa(monto,codigo);
                   //System.out.println(monto);
                   //System.out.println(codigo);
                }else{
                   JOptionPane.showMessageDialog(null, "CAMPO DE MONTO VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);              
                 }
             
                //SI LA RESPUESTA ES "NO"
            }else if(resp == JOptionPane.NO_OPTION){
            
              
            }          
        }else if (NuevaTazaBT.isSelected()){
            int resp = JOptionPane.showConfirmDialog(null, "SE VA A PROCEDER A CREAR UNA NUEVA TAZA\n"+"¿ESTA SEGURO?",
            "CREACION DE MONTO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE/*El tipo de ventana, en este caso WARNING*/);
            //SI LA RESPUESTA ES "YES"
            if(resp == JOptionPane.YES_OPTION){
              //VERIFICAR SI LOS CAMPOS ESTAN VACIOS
                if(!Montotxt.getText().isEmpty() && !DiaTXT.getText().isEmpty() && DiaTXT.getText().charAt(0) != 'D' && !Semanatxt.getText().isEmpty()){
                    String fecha = DiaTXT.getText();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    SimpleDateFormat output = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    Date data;
                    String dateFinal = "";
                    try {
                        data = sdf.parse(fecha);
                        dateFinal = output.format(data);
                    } catch (ParseException ex) {
                        Logger.getLogger(TasaBsUSD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    System.out.println(dateFinal);
                    String semana = Semanatxt.getText();
                    double monto = Double.parseDouble(Montotxt.getText());
                    monto = (double)Math.round(monto*100d)/100;
                    
                    try{
                        tasaObjeto.NuevaTasa(dateFinal, semana, monto);
                    } catch (Exception ex) {
                        Logger.getLogger(TasaBsUSD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }else{
                   JOptionPane.showMessageDialog(null, "ASEGURESE DE TENER TODOS LOS CAMPOS LLENOS", "ERROR", JOptionPane.ERROR_MESSAGE); 
                }    
            }else{
                                
            }
        }
        reestablecerPagina();
    }//GEN-LAST:event_AgregarBTActionPerformed

    private void CancelarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarBTActionPerformed

    private void LimpiarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarbtActionPerformed
        reestablecerPagina();
    }//GEN-LAST:event_LimpiarbtActionPerformed

    private void DiaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaTXTActionPerformed
    
    private void reestablecerPagina(){
        CodTazatxt.setText("");
        DiaTXT.setText("");
        Semanatxt.setText("");
        Montotxt.setText("");
        SeleccionarBT.setEnabled(true);
        AgregarBT.setEnabled(false);
        SeleccionarBT.setSelected(false);
        CambiatMontoBT.setSelected(false);
        AgregarBT.setSelected(false);
        NuevaTazaBT.setSelected(false);
        NuevaTazaBT.setEnabled(true);
        tabla.setVisible(true);
        updateTabla();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TasaBsUSD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TasaBsUSD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TasaBsUSD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TasaBsUSD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TasaBsUSD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBT;
    private javax.swing.JToggleButton CambiatMontoBT;
    private javax.swing.JButton CancelarBT;
    private javax.swing.JLabel CodTazaLB;
    private javax.swing.JTextField CodTazatxt;
    private javax.swing.JLabel DiaLB;
    private javax.swing.JTextField DiaTXT;
    private javax.swing.JButton Limpiarbt;
    private javax.swing.JTextField Montotxt;
    private javax.swing.JToggleButton NuevaTazaBT;
    private javax.swing.JToggleButton SeleccionarBT;
    private javax.swing.JLabel SemanaLB;
    private javax.swing.JTextField Semanatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel montoLB;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
