/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases.Odp;

import java.util.ArrayList;
import logica.ODP;

/**
 *
 * @author DANIEL
 */
public class SemanaODP extends javax.swing.JFrame {

    public int modo_pantalla;
    private ODP odpObjeto = new ODP();
    private String semana;
    private PlantillaPago PP;
    public SemanaODP() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        IconoCalendar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IconoPay = new javax.swing.JLabel();
        AceptarBT = new javax.swing.JButton();
        Semanas_CB = new javax.swing.JComboBox<>();
        Moneda_CB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        IconoCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calendar.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("INDIQUE LA SEMANA DE LA ORDEN DE PAGO");

        IconoPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pay'.png"))); // NOI18N

        AceptarBT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AceptarBT.setText("ACEPTAR");
        AceptarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBTActionPerformed(evt);
            }
        });

        Semanas_CB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Semanas_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        Moneda_CB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Moneda_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS", "DS" }));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoCalendar)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Semanas_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Moneda_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(AceptarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(IconoPay)
                .addGap(36, 36, 36))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Semanas_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Moneda_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AceptarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IconoPay)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(IconoCalendar)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        generarSemanas();
        if(modo_pantalla == 2){
            Moneda_CB.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void AceptarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBTActionPerformed
        if(Semanas_CB.getSelectedIndex() != 0){
            if(modo_pantalla == 1){
                semana = Semanas_CB.getSelectedItem().toString();
                PP = new PlantillaPago();
                if(Moneda_CB.getSelectedIndex() == 0){
                    PP.modo = 1;
                } else {
                    PP.modo = 2;
                }
                PP.semana = this.semana;
                PP.setVisible(true);
                this.dispose();
            } else {          
                semana = Semanas_CB.getSelectedItem().toString();
                PP = new PlantillaPago();
                PP.modo = 3;
                PP.semana = this.semana;
                PP.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_AceptarBTActionPerformed

    private void generarSemanas(){
        
        ArrayList<String> semanas = odpObjeto.semanasTransacciones();
        for(int i = 0; i < semanas.size(); i++){
            String item = semanas.get(i);
            Semanas_CB.addItem(item);
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemanaODP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemanaODP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemanaODP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemanaODP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SemanaODP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBT;
    private javax.swing.JLabel IconoCalendar;
    private javax.swing.JLabel IconoPay;
    private javax.swing.JComboBox<String> Moneda_CB;
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> Semanas_CB;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
